<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class DesignationsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('designations')->delete();
        
        \DB::table('designations')->insert(array (
            0 => 
            array (
                'id' => 1,
                'serial' => 1,
                'bn_name' => 'মহাপরিচালক',
                'en_name' => 'Director General ',
                'short_name' => 'DG',
                'pay_scale' => 'Grade-03',
                'status' => 'active',
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2021-01-20 10:40:20',
                'updated_at' => '2021-01-20 10:40:20',
                'deleted_at' => '2021-01-20 10:40:20',
            ),
            1 => 
            array (
                'id' => 2,
                'serial' => 2,
                'bn_name' => 'পরিচালক',
                'en_name' => 'Director   ',
                'short_name' => '',
                'pay_scale' => 'Grade-05',
                'status' => 'active',
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2021-01-20 10:40:20',
                'updated_at' => '2021-01-20 10:40:20',
                'deleted_at' => '2021-01-20 10:40:20',
            ),
            2 => 
            array (
                'id' => 3,
                'serial' => 3,
                'bn_name' => 'উপপরিচালক',
                'en_name' => 'Deputy Director',
                'short_name' => 'DD',
                'pay_scale' => 'Grade-06',
                'status' => 'active',
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2021-01-20 10:40:20',
                'updated_at' => '2021-01-20 10:40:20',
                'deleted_at' => '2021-01-20 10:40:20',
            ),
            3 => 
            array (
                'id' => 4,
                'serial' => 4,
                'bn_name' => 'অধ্যক্ষ',
                'en_name' => 'Principal ',
                'short_name' => '',
                'pay_scale' => 'Grade-06',
                'status' => 'active',
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2021-01-20 10:40:20',
                'updated_at' => '2021-01-20 10:40:20',
                'deleted_at' => '2021-01-20 10:40:20',
            ),
            4 => 
            array (
                'id' => 5,
                'serial' => 5,
                'bn_name' => 'সহকারী পরিচালক',
                'en_name' => 'Assistant Director ',
                'short_name' => 'AD',
                'pay_scale' => 'Grade-07',
                'status' => 'active',
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2021-01-20 10:40:20',
                'updated_at' => '2021-01-20 10:40:20',
                'deleted_at' => '2021-01-20 10:40:20',
            ),
            5 => 
            array (
                'id' => 6,
                'serial' => 6,
            'bn_name' => 'উপধ্যক্ষ (ট্রেনিং কমপ্লেক্স)',
                'en_name' => 'Vice Principal ',
                'short_name' => 'VP',
                'pay_scale' => 'Grade-07',
                'status' => 'active',
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2021-01-20 10:40:20',
                'updated_at' => '2021-01-20 10:40:20',
                'deleted_at' => '2021-01-20 10:40:20',
            ),
            6 => 
            array (
                'id' => 7,
                'serial' => 7,
                'bn_name' => 'সহকারী রক্ষণাবেক্ষণ প্রকৌশলী',
                'en_name' => 'Assistant Maintainance Engineer',
                'short_name' => '',
                'pay_scale' => 'Grade-09',
                'status' => 'active',
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2021-01-20 10:40:20',
                'updated_at' => '2021-01-20 10:40:20',
                'deleted_at' => '2021-01-20 10:40:20',
            ),
            7 => 
            array (
                'id' => 8,
                'serial' => 8,
                'bn_name' => 'উপসহকারী পরিচালক',
                'en_name' => 'Deputy Assistant Director ',
                'short_name' => 'DAD ',
                'pay_scale' => 'Grade-10',
                'status' => 'active',
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2021-01-20 10:40:20',
                'updated_at' => '2021-01-20 10:40:20',
                'deleted_at' => '2021-01-20 10:40:20',
            ),
            8 => 
            array (
                'id' => 9,
                'serial' => 9,
            'bn_name' => 'প্রশিক্ষক (ট্রেনিং কমপ্লেক্স)',
            'en_name' => 'Instructor (Training Complex) ',
                'short_name' => '',
                'pay_scale' => 'Grade-10',
                'status' => 'active',
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2021-01-20 10:40:20',
                'updated_at' => '2021-01-20 10:40:20',
                'deleted_at' => '2021-01-20 10:40:20',
            ),
            9 => 
            array (
                'id' => 10,
                'serial' => 10,
                'bn_name' => 'প্রোগ্রাম অর্গানাইজার কাম এ্যাডজুটেন্ট',
                'en_name' => 'Program Organizer Cum Adjutant',
                'short_name' => '',
                'pay_scale' => 'Grade-10',
                'status' => 'active',
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2021-01-20 10:40:20',
                'updated_at' => '2021-01-20 10:40:20',
                'deleted_at' => '2021-01-20 10:40:20',
            ),
            10 => 
            array (
                'id' => 11,
                'serial' => 11,
                'bn_name' => 'সিনিয়র স্টাফ অফিসার',
                'en_name' => 'Senior Staff Officer',
                'short_name' => '',
                'pay_scale' => 'Grade-10',
                'status' => 'active',
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2021-01-20 10:40:20',
                'updated_at' => '2021-01-20 10:40:20',
                'deleted_at' => '2021-01-20 10:40:20',
            ),
            11 => 
            array (
                'id' => 12,
                'serial' => 12,
                'bn_name' => 'মেকানিক্যাল ট্রান্সপোর্ট অফিসার',
                'en_name' => 'Mechanical Transport Officer',
                'short_name' => 'MTO',
                'pay_scale' => 'Grade-10',
                'status' => 'active',
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2021-01-20 10:40:20',
                'updated_at' => '2021-01-20 10:40:20',
                'deleted_at' => '2021-01-20 10:40:20',
            ),
            12 => 
            array (
                'id' => 13,
                'serial' => 13,
                'bn_name' => 'হিসাবরক্ষণ কর্মকর্তা',
                'en_name' => 'Accounts Officer',
                'short_name' => '',
                'pay_scale' => 'Grade-10',
                'status' => 'active',
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2021-01-20 10:40:20',
                'updated_at' => '2021-01-20 10:40:20',
                'deleted_at' => '2021-01-20 10:40:20',
            ),
            13 => 
            array (
                'id' => 14,
                'serial' => 14,
                'bn_name' => 'প্রশাসনিক কর্মকর্তা',
                'en_name' => 'Administrative Officer',
                'short_name' => 'AO',
                'pay_scale' => 'Grade-11',
                'status' => 'active',
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2021-01-20 10:40:20',
                'updated_at' => '2021-01-20 10:40:20',
                'deleted_at' => '2021-01-20 10:40:20',
            ),
            14 => 
            array (
                'id' => 15,
                'serial' => 15,
                'bn_name' => 'ফোরম্যান',
                'en_name' => 'Foreman ',
                'short_name' => '',
                'pay_scale' => 'Grade-10',
                'status' => 'active',
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2021-01-20 10:40:20',
                'updated_at' => '2021-01-20 10:40:20',
                'deleted_at' => '2021-01-20 10:40:20',
            ),
            15 => 
            array (
                'id' => 16,
                'serial' => 16,
                'bn_name' => 'সিনিয়র স্টেশন অফিসার ',
                'en_name' => 'Senior Station Officer ',
                'short_name' => 'SSO',
                'pay_scale' => 'Grade-11',
                'status' => 'active',
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2021-01-20 10:40:20',
                'updated_at' => '2021-01-20 10:40:20',
                'deleted_at' => '2021-01-20 10:40:20',
            ),
            16 => 
            array (
                'id' => 17,
                'serial' => 17,
            'bn_name' => 'সহকারী প্রশিক্ষক (ট্রেনিং কমপ্লেক্স) ',
            'en_name' => 'Assistant Instructor (Training Complex) ',
                'short_name' => '',
                'pay_scale' => 'Grade-11',
                'status' => 'active',
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2021-01-20 10:40:20',
                'updated_at' => '2021-01-20 10:40:20',
                'deleted_at' => '2021-01-20 10:40:20',
            ),
            17 => 
            array (
                'id' => 18,
                'serial' => 18,
                'bn_name' => 'স্টোর অফিসার ',
                'en_name' => 'Store Officer',
                'short_name' => '',
                'pay_scale' => 'Grade-11',
                'status' => 'active',
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2021-01-20 10:40:20',
                'updated_at' => '2021-01-20 10:40:20',
                'deleted_at' => '2021-01-20 10:40:20',
            ),
            18 => 
            array (
                'id' => 19,
                'serial' => 19,
            'bn_name' => 'ভারপ্রাপ্ত কর্মকর্তা (কেন্দ্রীয় নিয়ন্ত্রণ কক্ষ)',
            'en_name' => 'Officer Incharge (Central Control Room) ',
                'short_name' => '',
                'pay_scale' => 'Grade-11',
                'status' => 'active',
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2021-01-20 10:40:20',
                'updated_at' => '2021-01-20 10:40:20',
                'deleted_at' => '2021-01-20 10:40:20',
            ),
            19 => 
            array (
                'id' => 20,
                'serial' => 20,
            'bn_name' => 'সহকারী যোগাযোগ প্রকৌশলী)',
            'en_name' => 'Assistant Communication Engineer',
            'short_name' => '',
            'pay_scale' => 'Grade-10',
            'status' => 'active',
            'created_by' => 2,
            'updated_by' => 2,
            'created_at' => '2021-01-20 10:40:20',
            'updated_at' => '2021-01-20 10:40:20',
            'deleted_at' => '2021-01-20 10:40:20',
        ),
        20 => 
        array (
            'id' => 21,
            'serial' => 21,
        'bn_name' => 'ড্রাইভার ইন্সট্রাক্টর (ট্রেনিং কমপ্লেক্স)',
        'en_name' => 'Driver Instructor (Training Complex) ',
            'short_name' => '',
            'pay_scale' => 'Grade-12',
            'status' => 'active',
            'created_by' => 2,
            'updated_by' => 2,
            'created_at' => '2021-01-20 10:40:20',
            'updated_at' => '2021-01-20 10:40:20',
            'deleted_at' => '2021-01-20 10:40:20',
        ),
        21 => 
        array (
            'id' => 22,
            'serial' => 22,
        'bn_name' => 'ফিজিক্যাল ইন্সট্রাক্টর (ট্রেনিং কমপ্লেক্স)',
        'en_name' => 'Physical Instructor (Training Complex )',
            'short_name' => '',
            'pay_scale' => 'Grade-12',
            'status' => 'active',
            'created_by' => 2,
            'updated_by' => 2,
            'created_at' => '2021-01-20 10:40:20',
            'updated_at' => '2021-01-20 10:40:20',
            'deleted_at' => '2021-01-20 10:40:20',
        ),
        22 => 
        array (
            'id' => 23,
            'serial' => 23,
            'bn_name' => 'ওয়্যারহাউজ ইন্সপেক্টর ',
            'en_name' => 'Werehouse Inspector ',
            'short_name' => 'WHI',
            'pay_scale' => 'Grade-11',
            'status' => 'active',
            'created_by' => 2,
            'updated_by' => 2,
            'created_at' => '2021-01-20 10:40:20',
            'updated_at' => '2021-01-20 10:40:20',
            'deleted_at' => '2021-01-20 10:40:20',
        ),
        23 => 
        array (
            'id' => 24,
            'serial' => 24,
        'bn_name' => 'উপসহকারী যোগাযোগ প্রকৌশলী (গ্রেড-১০)',
        'en_name' => 'Sub-Assistant Communication Engineer (Grade-10)',
            'short_name' => '',
            'pay_scale' => 'Grade-10',
            'status' => 'active',
            'created_by' => 2,
            'updated_by' => 2,
            'created_at' => '2021-01-20 10:40:20',
            'updated_at' => '2021-01-20 10:40:20',
            'deleted_at' => '2021-01-20 10:40:20',
        ),
        24 => 
        array (
            'id' => 25,
            'serial' => 25,
        'bn_name' => 'উপসহকারী যোগাযোগ প্রকৌশলী (গ্রেড-১১)',
        'en_name' => 'Sub-Assistant Communication Engineer (Grade-11)',
            'short_name' => '',
            'pay_scale' => 'Grade-11',
            'status' => 'active',
            'created_by' => 2,
            'updated_by' => 2,
            'created_at' => '2021-01-20 10:40:20',
            'updated_at' => '2021-01-20 10:40:20',
            'deleted_at' => '2021-01-20 10:40:20',
        ),
        25 => 
        array (
            'id' => 26,
            'serial' => 26,
            'bn_name' => 'স্টেশন অফিসার',
            'en_name' => 'Station Officer',
            'short_name' => 'SO',
            'pay_scale' => 'Grade-12',
            'status' => 'active',
            'created_by' => 2,
            'updated_by' => 2,
            'created_at' => '2021-01-20 10:40:20',
            'updated_at' => '2021-01-20 10:40:20',
            'deleted_at' => '2021-01-20 10:40:20',
        ),
        26 => 
        array (
            'id' => 27,
            'serial' => 27,
            'bn_name' => 'স্টাফ অফিসার ',
            'en_name' => 'Staff Officer',
            'short_name' => 'STO',
            'pay_scale' => 'Grade-12',
            'status' => 'active',
            'created_by' => 2,
            'updated_by' => 2,
            'created_at' => '2021-01-20 10:40:20',
            'updated_at' => '2021-01-20 10:40:20',
            'deleted_at' => '2021-01-20 10:40:20',
        ),
        27 => 
        array (
            'id' => 28,
            'serial' => 28,
            'bn_name' => 'মবিলাইজিং অফিসার',
            'en_name' => 'Mobilizing Officer ',
            'short_name' => 'MO',
            'pay_scale' => 'Grade-12',
            'status' => 'active',
            'created_by' => 2,
            'updated_by' => 2,
            'created_at' => '2021-01-20 10:40:20',
            'updated_at' => '2021-01-20 10:40:20',
            'deleted_at' => '2021-01-20 10:40:20',
        ),
        28 => 
        array (
            'id' => 29,
            'serial' => 29,
            'bn_name' => 'জুনিয়র প্রশিক্ষক',
        'en_name' => 'Junior Instructor (Training Complex) ',
            'short_name' => 'JI',
            'pay_scale' => 'Grade-12',
            'status' => 'active',
            'created_by' => 2,
            'updated_by' => 2,
            'created_at' => '2021-01-20 10:40:20',
            'updated_at' => '2021-01-20 10:40:20',
            'deleted_at' => '2021-01-20 10:40:20',
        ),
        29 => 
        array (
            'id' => 30,
            'serial' => 30,
        'bn_name' => 'সুপারিনটেনডেন্ট (তত্বাবধায়ক)',
            'en_name' => 'Superintendent ',
            'short_name' => '',
            'pay_scale' => 'Grade-13',
            'status' => 'active',
            'created_by' => 2,
            'updated_by' => 2,
            'created_at' => '2021-01-20 10:40:20',
            'updated_at' => '2021-01-20 10:40:20',
            'deleted_at' => '2021-01-20 10:40:20',
        ),
        30 => 
        array (
            'id' => 31,
            'serial' => 31,
        'bn_name' => 'হিসাবরক্ষক (গ্রেড-১৩)',
        'en_name' => 'Accountent (Grade-13)',
            'short_name' => '',
            'pay_scale' => 'Grade-13',
            'status' => 'active',
            'created_by' => 2,
            'updated_by' => 2,
            'created_at' => '2021-01-20 10:40:20',
            'updated_at' => '2021-01-20 10:40:20',
            'deleted_at' => '2021-01-20 10:40:20',
        ),
        31 => 
        array (
            'id' => 32,
            'serial' => 32,
            'bn_name' => 'হিসাবরক্ষক কাম কোষাধ্যক্ষ ',
        'en_name' => 'Accountant cum Cashier (Grade-13)',
            'short_name' => '',
            'pay_scale' => 'Grade-13',
            'status' => 'active',
            'created_by' => 2,
            'updated_by' => 2,
            'created_at' => '2021-01-20 10:40:20',
            'updated_at' => '2021-01-20 10:40:20',
            'deleted_at' => '2021-01-20 10:40:20',
        ),
        32 => 
        array (
            'id' => 33,
            'serial' => 33,
            'bn_name' => 'সাঁট-লিপিকার কাম-কম্পিউটার অপারেটর',
            'en_name' => 'Stenographer cum Computer Operator',
            'short_name' => '',
            'pay_scale' => 'Grade-13',
            'status' => 'active',
            'created_by' => 2,
            'updated_by' => 2,
            'created_at' => '2021-01-20 10:40:20',
            'updated_at' => '2021-01-20 10:40:20',
            'deleted_at' => '2021-01-20 10:40:20',
        ),
        33 => 
        array (
            'id' => 34,
            'serial' => 34,
            'bn_name' => 'ড্রাফটসম্যান',
            'en_name' => 'Draftsman',
            'short_name' => '',
            'pay_scale' => 'Grade-13',
            'status' => 'active',
            'created_by' => 2,
            'updated_by' => 2,
            'created_at' => '2021-01-20 10:40:20',
            'updated_at' => '2021-01-20 10:40:20',
            'deleted_at' => '2021-01-20 10:40:20',
        ),
        34 => 
        array (
            'id' => 35,
            'serial' => 35,
            'bn_name' => 'সাঁট-মুদ্রাক্ষরিক কাম কম্পিউটার অপারেটর ',
            'en_name' => 'Steno Typist cum Computer Operator ',
            'short_name' => '',
            'pay_scale' => 'Grade-14',
            'status' => 'active',
            'created_by' => 2,
            'updated_by' => 2,
            'created_at' => '2021-01-20 10:40:20',
            'updated_at' => '2021-01-20 10:40:20',
            'deleted_at' => '2021-01-20 10:40:20',
        ),
        35 => 
        array (
            'id' => 36,
            'serial' => 36,
            'bn_name' => 'হিসাবরক্ষক-কাম-ক্যাশিয়ার ',
        'en_name' => 'Accountent cum Cashier (Grade-14)',
            'short_name' => '',
            'pay_scale' => 'Grade-14',
            'status' => 'active',
            'created_by' => 2,
            'updated_by' => 2,
            'created_at' => '2021-01-20 10:40:20',
            'updated_at' => '2021-01-20 10:40:20',
            'deleted_at' => '2021-01-20 10:40:20',
        ),
        36 => 
        array (
            'id' => 37,
            'serial' => 37,
        'bn_name' => 'হিসাবরক্ষক (গ্রেড-১৪)',
        'en_name' => 'Accountent (Grade-14)',
            'short_name' => '',
            'pay_scale' => 'Grade-14',
            'status' => 'active',
            'created_by' => 2,
            'updated_by' => 2,
            'created_at' => '2021-01-20 10:40:20',
            'updated_at' => '2021-01-20 10:40:20',
            'deleted_at' => '2021-01-20 10:40:20',
        ),
        37 => 
        array (
            'id' => 38,
            'serial' => 38,
            'bn_name' => 'উচ্চমান সহঃ কাম-ক্যাশিয়ার ',
            'en_name' => 'Upper Divisional Assistant Cum Cashier',
            'short_name' => '',
            'pay_scale' => 'Grade-14',
            'status' => 'active',
            'created_by' => 2,
            'updated_by' => 2,
            'created_at' => '2021-01-20 10:40:20',
            'updated_at' => '2021-01-20 10:40:20',
            'deleted_at' => '2021-01-20 10:40:20',
        ),
        38 => 
        array (
            'id' => 39,
            'serial' => 39,
            'bn_name' => 'উচ্চমান সহকারী ',
            'en_name' => 'Upper Divisional Assistant ',
            'short_name' => 'UDA',
            'pay_scale' => 'Grade-14',
            'status' => 'active',
            'created_by' => 2,
            'updated_by' => 2,
            'created_at' => '2021-01-20 10:40:20',
            'updated_at' => '2021-01-20 10:40:20',
            'deleted_at' => '2021-01-20 10:40:20',
        ),
        39 => 
        array (
            'id' => 40,
            'serial' => 40,
            'bn_name' => 'পরিসংখ্যান সহকারী',
            'en_name' => 'Statistics Assistant',
            'short_name' => '',
            'pay_scale' => 'Grade-14',
            'status' => 'active',
            'created_by' => 2,
            'updated_by' => 2,
            'created_at' => '2021-01-20 10:40:20',
            'updated_at' => '2021-01-20 10:40:20',
            'deleted_at' => '2021-01-20 10:40:20',
        ),
        40 => 
        array (
            'id' => 41,
            'serial' => 41,
        'bn_name' => 'ধর্মীয় শিক্ষক (ইসলাম)',
        'en_name' => 'Religious Teacher (Islam) ',
            'short_name' => '',
            'pay_scale' => 'Grade-15',
            'status' => 'active',
            'created_by' => 2,
            'updated_by' => 2,
            'created_at' => '2021-01-20 10:40:20',
            'updated_at' => '2021-01-20 10:40:20',
            'deleted_at' => '2021-01-20 10:40:20',
        ),
        41 => 
        array (
            'id' => 42,
            'serial' => 42,
            'bn_name' => 'সাব-অফিসার ',
            'en_name' => 'Sub-Officer ',
            'short_name' => '',
            'pay_scale' => 'Grade-15',
            'status' => 'active',
            'created_by' => 2,
            'updated_by' => 2,
            'created_at' => '2021-01-20 10:40:20',
            'updated_at' => '2021-01-20 10:40:20',
            'deleted_at' => '2021-01-20 10:40:20',
        ),
        42 => 
        array (
            'id' => 43,
            'serial' => 43,
            'bn_name' => 'ডেমোনস্ট্রেটর ',
            'en_name' => 'Demonstrator ',
            'short_name' => '',
            'pay_scale' => 'Grade-15',
            'status' => 'active',
            'created_by' => 2,
            'updated_by' => 2,
            'created_at' => '2021-01-20 10:40:20',
            'updated_at' => '2021-01-20 10:40:20',
            'deleted_at' => '2021-01-20 10:40:20',
        ),
        43 => 
        array (
            'id' => 44,
            'serial' => 44,
        'bn_name' => 'মাস্টার ড্রাইভার (মেরিন) ',
        'en_name' => 'Master Driver (Marine) ',
            'short_name' => '',
            'pay_scale' => 'Grade-15',
            'status' => 'active',
            'created_by' => 2,
            'updated_by' => 2,
            'created_at' => '2021-01-20 10:40:20',
            'updated_at' => '2021-01-20 10:40:20',
            'deleted_at' => '2021-01-20 10:40:20',
        ),
        44 => 
        array (
            'id' => 45,
            'serial' => 45,
        'bn_name' => 'ইন্জিন ড্রাইভার (মেরিন)',
        'en_name' => 'Engine Driver (Marine)',
            'short_name' => '',
            'pay_scale' => 'Grade-15',
            'status' => 'active',
            'created_by' => 2,
            'updated_by' => 2,
            'created_at' => '2021-01-20 10:40:20',
            'updated_at' => '2021-01-20 10:40:20',
            'deleted_at' => '2021-01-20 10:40:20',
        ),
        45 => 
        array (
            'id' => 46,
            'serial' => 46,
            'bn_name' => 'স্পীডবোট ড্রাইভার ',
            'en_name' => 'Speed Boat Driver ',
            'short_name' => '',
            'pay_scale' => 'Grade-15',
            'status' => 'active',
            'created_by' => 2,
            'updated_by' => 2,
            'created_at' => '2021-01-20 10:40:20',
            'updated_at' => '2021-01-20 10:40:20',
            'deleted_at' => '2021-01-20 10:40:20',
        ),
        46 => 
        array (
            'id' => 47,
            'serial' => 47,
            'bn_name' => 'হেড মেকানিক ',
            'en_name' => 'Head Mechanic',
            'short_name' => '',
            'pay_scale' => 'Grade-15',
            'status' => 'active',
            'created_by' => 2,
            'updated_by' => 2,
            'created_at' => '2021-01-20 10:40:20',
            'updated_at' => '2021-01-20 10:40:20',
            'deleted_at' => '2021-01-20 10:40:20',
        ),
        47 => 
        array (
            'id' => 48,
            'serial' => 48,
            'bn_name' => 'মেকানিক ',
            'en_name' => 'Mechanic ',
            'short_name' => '',
            'pay_scale' => 'Grade-15',
            'status' => 'active',
            'created_by' => 2,
            'updated_by' => 2,
            'created_at' => '2021-01-20 10:40:20',
            'updated_at' => '2021-01-20 10:40:20',
            'deleted_at' => '2021-01-20 10:40:20',
        ),
        48 => 
        array (
            'id' => 49,
            'serial' => 49,
            'bn_name' => 'সহকারী মেকানিক ',
            'en_name' => 'Assistant Mechanic ',
            'short_name' => '',
            'pay_scale' => 'Grade-15',
            'status' => 'active',
            'created_by' => 2,
            'updated_by' => 2,
            'created_at' => '2021-01-20 10:40:20',
            'updated_at' => '2021-01-20 10:40:20',
            'deleted_at' => '2021-01-20 10:40:20',
        ),
        49 => 
        array (
            'id' => 50,
            'serial' => 50,
            'bn_name' => 'বোরিং মেশিনম্যঅন ',
            'en_name' => 'Boring Machineman',
            'short_name' => '',
            'pay_scale' => 'Grade-15',
            'status' => 'active',
            'created_by' => 2,
            'updated_by' => 2,
            'created_at' => '2021-01-20 10:40:20',
            'updated_at' => '2021-01-20 10:40:20',
            'deleted_at' => '2021-01-20 10:40:20',
        ),
        50 => 
        array (
            'id' => 51,
            'serial' => 51,
            'bn_name' => 'লেদ মেশিনশ্যান ',
            'en_name' => 'Lathe Machineman',
            'short_name' => '',
            'pay_scale' => 'Grade-15',
            'status' => 'active',
            'created_by' => 2,
            'updated_by' => 2,
            'created_at' => '2021-01-20 10:40:20',
            'updated_at' => '2021-01-20 10:40:20',
            'deleted_at' => '2021-01-20 10:40:20',
        ),
        51 => 
        array (
            'id' => 52,
            'serial' => 52,
            'bn_name' => 'মিলিং মেশিনম্যান',
            'en_name' => 'Milling Machineman',
            'short_name' => '',
            'pay_scale' => 'Grade-15',
            'status' => 'active',
            'created_by' => 2,
            'updated_by' => 2,
            'created_at' => '2021-01-20 10:40:20',
            'updated_at' => '2021-01-20 10:40:20',
            'deleted_at' => '2021-01-20 10:40:20',
        ),
        52 => 
        array (
            'id' => 53,
            'serial' => 53,
            'bn_name' => 'মোল্ডার ',
            'en_name' => 'Moulder',
            'short_name' => '',
            'pay_scale' => 'Grade-15',
            'status' => 'active',
            'created_by' => 2,
            'updated_by' => 2,
            'created_at' => '2021-01-20 10:40:20',
            'updated_at' => '2021-01-20 10:40:20',
            'deleted_at' => '2021-01-20 10:40:20',
        ),
        53 => 
        array (
            'id' => 54,
            'serial' => 54,
            'bn_name' => 'বডি এ্যান্ড কোচ বিল্ডার',
            'en_name' => 'Body and Couch Builder',
            'short_name' => '',
            'pay_scale' => 'Grade-15',
            'status' => 'active',
            'created_by' => 2,
            'updated_by' => 2,
            'created_at' => '2021-01-20 10:40:20',
            'updated_at' => '2021-01-20 10:40:20',
            'deleted_at' => '2021-01-20 10:40:20',
        ),
        54 => 
        array (
            'id' => 55,
            'serial' => 55,
            'bn_name' => 'আর্মেচার বাইন্ডার ',
            'en_name' => 'Armature Binder ',
            'short_name' => '',
            'pay_scale' => 'Grade-15',
            'status' => 'active',
            'created_by' => 2,
            'updated_by' => 2,
            'created_at' => '2021-01-20 10:40:20',
            'updated_at' => '2021-01-20 10:40:20',
            'deleted_at' => '2021-01-20 10:40:20',
        ),
        55 => 
        array (
            'id' => 56,
            'serial' => 56,
            'bn_name' => 'সিনেমা অপারেটার',
            'en_name' => 'Cinema Operator ',
            'short_name' => '',
            'pay_scale' => 'Grade-15',
            'status' => 'active',
            'created_by' => 2,
            'updated_by' => 2,
            'created_at' => '2021-01-20 10:40:20',
            'updated_at' => '2021-01-20 10:40:20',
            'deleted_at' => '2021-01-20 10:40:20',
        ),
        56 => 
        array (
            'id' => 57,
            'serial' => 57,
            'bn_name' => 'ওয়্যারলেস মেকানিক ',
            'en_name' => 'Wireless Mechanic ',
            'short_name' => '',
            'pay_scale' => 'Grade-15',
            'status' => 'active',
            'created_by' => 2,
            'updated_by' => 2,
            'created_at' => '2021-01-20 10:40:20',
            'updated_at' => '2021-01-20 10:40:20',
            'deleted_at' => '2021-01-20 10:40:20',
        ),
        57 => 
        array (
            'id' => 58,
            'serial' => 58,
            'bn_name' => 'ড্রাইভার  ',
            'en_name' => 'Driver   ',
            'short_name' => '',
            'pay_scale' => 'Grade-15',
            'status' => 'active',
            'created_by' => 2,
            'updated_by' => 2,
            'created_at' => '2021-01-20 10:40:20',
            'updated_at' => '2021-01-20 10:40:20',
            'deleted_at' => '2021-01-20 10:40:20',
        ),
        58 => 
        array (
            'id' => 59,
            'serial' => 59,
            'bn_name' => 'টেলিফোন অপারেটর',
            'en_name' => 'Telepohone Operator ',
            'short_name' => '',
            'pay_scale' => 'Grade-16',
            'status' => 'active',
            'created_by' => 2,
            'updated_by' => 2,
            'created_at' => '2021-01-20 10:40:20',
            'updated_at' => '2021-01-20 10:40:20',
            'deleted_at' => '2021-01-20 10:40:20',
        ),
        59 => 
        array (
            'id' => 60,
            'serial' => 60,
            'bn_name' => 'ওয়্যারলেস অপারেটর ',
            'en_name' => 'Wireless Operator ',
            'short_name' => '',
            'pay_scale' => 'Grade-16',
            'status' => 'active',
            'created_by' => 2,
            'updated_by' => 2,
            'created_at' => '2021-01-20 10:40:20',
            'updated_at' => '2021-01-20 10:40:20',
            'deleted_at' => '2021-01-20 10:40:20',
        ),
        60 => 
        array (
            'id' => 61,
            'serial' => 61,
            'bn_name' => 'অফিস সহকারী-কাম কম্পিউটার মুদ্রাক্ষরিক ',
            'en_name' => 'Office Assistant cum Computer Typist ',
            'short_name' => '',
            'pay_scale' => 'Grade-16',
            'status' => 'active',
            'created_by' => 2,
            'updated_by' => 2,
            'created_at' => '2021-01-20 10:40:20',
            'updated_at' => '2021-01-20 10:40:20',
            'deleted_at' => '2021-01-20 10:40:20',
        ),
        61 => 
        array (
            'id' => 62,
            'serial' => 62,
            'bn_name' => 'অফিস সহকারী ',
            'en_name' => 'Office Assistant  ',
            'short_name' => '',
            'pay_scale' => 'Grade-16',
            'status' => 'active',
            'created_by' => 2,
            'updated_by' => 2,
            'created_at' => '2021-01-20 10:40:20',
            'updated_at' => '2021-01-20 10:40:20',
            'deleted_at' => '2021-01-20 10:40:20',
        ),
        62 => 
        array (
            'id' => 63,
            'serial' => 63,
        'bn_name' => 'অফিস সহকারী কাম কম্পিউটার মুদ্রাক্ষরিক (কম্পিউটার মুদ্রাক্ষরিক)',
        'en_name' => 'Office Assistant cum Computer Typist (Computer Typist)',
            'short_name' => '',
            'pay_scale' => 'Grade-16',
            'status' => 'active',
            'created_by' => 2,
            'updated_by' => 2,
            'created_at' => '2021-01-20 10:40:20',
            'updated_at' => '2021-01-20 10:40:20',
            'deleted_at' => '2021-01-20 10:40:20',
        ),
        63 => 
        array (
            'id' => 64,
            'serial' => 64,
            'bn_name' => 'স্টোর কিপার ',
            'en_name' => 'Store Keeper ',
            'short_name' => '',
            'pay_scale' => 'Grade-16',
            'status' => 'active',
            'created_by' => 2,
            'updated_by' => 2,
            'created_at' => '2021-01-20 10:40:20',
            'updated_at' => '2021-01-20 10:40:20',
            'deleted_at' => '2021-01-20 10:40:20',
        ),
        64 => 
        array (
            'id' => 65,
            'serial' => 65,
            'bn_name' => 'স্টোর সহকারী ',
            'en_name' => 'Store Assistant ',
            'short_name' => '',
            'pay_scale' => 'Grade-16',
            'status' => 'active',
            'created_by' => 2,
            'updated_by' => 2,
            'created_at' => '2021-01-20 10:40:20',
            'updated_at' => '2021-01-20 10:40:20',
            'deleted_at' => '2021-01-20 10:40:20',
        ),
        65 => 
        array (
            'id' => 66,
            'serial' => 66,
            'bn_name' => 'লিডার ',
            'en_name' => 'Leader ',
            'short_name' => '',
            'pay_scale' => 'Grade-16',
            'status' => 'active',
            'created_by' => 2,
            'updated_by' => 2,
            'created_at' => '2021-01-20 10:40:20',
            'updated_at' => '2021-01-20 10:40:20',
            'deleted_at' => '2021-01-20 10:40:20',
        ),
        66 => 
        array (
            'id' => 67,
            'serial' => 67,
            'bn_name' => 'কার্পেন্টার',
            'en_name' => 'Carpenter ',
            'short_name' => '',
            'pay_scale' => 'Grade-16',
            'status' => 'active',
            'created_by' => 2,
            'updated_by' => 2,
            'created_at' => '2021-01-20 10:40:20',
            'updated_at' => '2021-01-20 10:40:20',
            'deleted_at' => '2021-01-20 10:40:20',
        ),
        67 => 
        array (
            'id' => 68,
            'serial' => 68,
            'bn_name' => 'ইলেকট্রিশিয়ান ',
            'en_name' => 'Electtrician ',
            'short_name' => '',
            'pay_scale' => 'Grade-17',
            'status' => 'active',
            'created_by' => 2,
            'updated_by' => 2,
            'created_at' => '2021-01-20 10:40:20',
            'updated_at' => '2021-01-20 10:40:20',
            'deleted_at' => '2021-01-20 10:40:20',
        ),
        68 => 
        array (
            'id' => 69,
            'serial' => 69,
            'bn_name' => 'স্প্রে পেইন্টার ',
            'en_name' => 'Spray Painter ',
            'short_name' => '',
            'pay_scale' => 'Grade-17',
            'status' => 'active',
            'created_by' => 2,
            'updated_by' => 2,
            'created_at' => '2021-01-20 10:40:20',
            'updated_at' => '2021-01-20 10:40:20',
            'deleted_at' => '2021-01-20 10:40:20',
        ),
        69 => 
        array (
            'id' => 70,
            'serial' => 70,
            'bn_name' => 'ওয়েল্ডার ',
            'en_name' => 'Welder',
            'short_name' => '',
            'pay_scale' => 'Grade-17',
            'status' => 'active',
            'created_by' => 2,
            'updated_by' => 2,
            'created_at' => '2021-01-20 10:40:20',
            'updated_at' => '2021-01-20 10:40:20',
            'deleted_at' => '2021-01-20 10:40:20',
        ),
        70 => 
        array (
            'id' => 71,
            'serial' => 71,
            'bn_name' => 'টার্নার ',
            'en_name' => 'Turner ',
            'short_name' => '',
            'pay_scale' => 'Grade-17',
            'status' => 'active',
            'created_by' => 2,
            'updated_by' => 2,
            'created_at' => '2021-01-20 10:40:20',
            'updated_at' => '2021-01-20 10:40:20',
            'deleted_at' => '2021-01-20 10:40:20',
        ),
        71 => 
        array (
            'id' => 72,
            'serial' => 72,
            'bn_name' => 'ফায়ারম্যান ',
            'en_name' => 'Fireman',
            'short_name' => '',
            'pay_scale' => 'Grade-17',
            'status' => 'active',
            'created_by' => 2,
            'updated_by' => 2,
            'created_at' => '2021-01-20 10:40:20',
            'updated_at' => '2021-01-20 10:40:20',
            'deleted_at' => '2021-01-20 10:40:20',
        ),
        72 => 
        array (
            'id' => 73,
            'serial' => 73,
            'bn_name' => 'ডুবুরি ',
            'en_name' => 'Diver',
            'short_name' => '',
            'pay_scale' => 'Grade-17',
            'status' => 'active',
            'created_by' => 2,
            'updated_by' => 2,
            'created_at' => '2021-01-20 10:40:20',
            'updated_at' => '2021-01-20 10:40:20',
            'deleted_at' => '2021-01-20 10:40:20',
        ),
        73 => 
        array (
            'id' => 74,
            'serial' => 74,
            'bn_name' => 'নার্সিং এটেনডেন্ট',
            'en_name' => 'Nursing Attendant ',
            'short_name' => '',
            'pay_scale' => 'Grade-17',
            'status' => 'active',
            'created_by' => 2,
            'updated_by' => 2,
            'created_at' => '2021-01-20 10:40:20',
            'updated_at' => '2021-01-20 10:40:20',
            'deleted_at' => '2021-01-20 10:40:20',
        ),
        74 => 
        array (
            'id' => 75,
            'serial' => 75,
            'bn_name' => 'টিন স্মিথ ',
            'en_name' => 'Tin Smith ',
            'short_name' => '',
            'pay_scale' => 'Grade-18',
            'status' => 'active',
            'created_by' => 2,
            'updated_by' => 2,
            'created_at' => '2021-01-20 10:40:20',
            'updated_at' => '2021-01-20 10:40:20',
            'deleted_at' => '2021-01-20 10:40:20',
        ),
        75 => 
        array (
            'id' => 76,
            'serial' => 76,
            'bn_name' => 'ব্লাক স্মিথ ',
            'en_name' => 'Black Smith',
            'short_name' => '',
            'pay_scale' => 'Grade-18',
            'status' => 'active',
            'created_by' => 2,
            'updated_by' => 2,
            'created_at' => '2021-01-20 10:40:20',
            'updated_at' => '2021-01-20 10:40:20',
            'deleted_at' => '2021-01-20 10:40:20',
        ),
        76 => 
        array (
            'id' => 77,
            'serial' => 77,
            'bn_name' => 'পেইন্টার ',
            'en_name' => 'Painter',
            'short_name' => '',
            'pay_scale' => 'Grade-18',
            'status' => 'active',
            'created_by' => 2,
            'updated_by' => 2,
            'created_at' => '2021-01-20 10:40:20',
            'updated_at' => '2021-01-20 10:40:20',
            'deleted_at' => '2021-01-20 10:40:20',
        ),
        77 => 
        array (
            'id' => 78,
            'serial' => 78,
            'bn_name' => 'হোজ রিপেয়ারার ',
            'en_name' => 'Hose Repairer ',
            'short_name' => '',
            'pay_scale' => 'Grade-18',
            'status' => 'active',
            'created_by' => 2,
            'updated_by' => 2,
            'created_at' => '2021-01-20 10:40:20',
            'updated_at' => '2021-01-20 10:40:20',
            'deleted_at' => '2021-01-20 10:40:20',
        ),
        78 => 
        array (
            'id' => 79,
            'serial' => 79,
            'bn_name' => 'ডেসপাস রাইডার ',
            'en_name' => 'Despass Raider ',
            'short_name' => '',
            'pay_scale' => 'Grade-18',
            'status' => 'active',
            'created_by' => 2,
            'updated_by' => 2,
            'created_at' => '2021-01-20 10:40:20',
            'updated_at' => '2021-01-20 10:40:20',
            'deleted_at' => '2021-01-20 10:40:20',
        ),
        79 => 
        array (
            'id' => 80,
            'serial' => 80,
            'bn_name' => 'ওয়ার্কশপ হেলপার ',
            'en_name' => 'Workshop Helper ',
            'short_name' => '',
            'pay_scale' => 'Grade-19',
            'status' => 'active',
            'created_by' => 2,
            'updated_by' => 2,
            'created_at' => '2021-01-20 10:40:20',
            'updated_at' => '2021-01-20 10:40:20',
            'deleted_at' => '2021-01-20 10:40:20',
        ),
        80 => 
        array (
            'id' => 81,
            'serial' => 81,
            'bn_name' => 'অফিস সহায়ক ',
            'en_name' => 'Office Sahayok',
            'short_name' => '',
            'pay_scale' => 'Grade-20',
            'status' => 'active',
            'created_by' => 2,
            'updated_by' => 2,
            'created_at' => '2021-01-20 10:40:20',
            'updated_at' => '2021-01-20 10:40:20',
            'deleted_at' => '2021-01-20 10:40:20',
        ),
        81 => 
        array (
            'id' => 82,
            'serial' => 82,
            'bn_name' => 'সহকারী হোজ রিপেয়ারার ',
            'en_name' => 'Assistant Hose Repairar ',
            'short_name' => '',
            'pay_scale' => 'Grade-20',
            'status' => 'active',
            'created_by' => 2,
            'updated_by' => 2,
            'created_at' => '2021-01-20 10:40:20',
            'updated_at' => '2021-01-20 10:40:20',
            'deleted_at' => '2021-01-20 10:40:20',
        ),
        82 => 
        array (
            'id' => 83,
            'serial' => 83,
            'bn_name' => 'ওজানদার ',
            'en_name' => 'Weightlifter',
            'short_name' => '',
            'pay_scale' => 'Grade-20',
            'status' => 'active',
            'created_by' => 2,
            'updated_by' => 2,
            'created_at' => '2021-01-20 10:40:20',
            'updated_at' => '2021-01-20 10:40:20',
            'deleted_at' => '2021-01-20 10:40:20',
        ),
        83 => 
        array (
            'id' => 84,
            'serial' => 84,
            'bn_name' => 'নিরাপত্তা প্রহরী ',
            'en_name' => 'Security Guard',
            'short_name' => '',
            'pay_scale' => 'Grade-20',
            'status' => 'active',
            'created_by' => 2,
            'updated_by' => 2,
            'created_at' => '2021-01-20 10:40:20',
            'updated_at' => '2021-01-20 10:40:20',
            'deleted_at' => '2021-01-20 10:40:20',
        ),
        84 => 
        array (
            'id' => 85,
            'serial' => 85,
            'bn_name' => 'বাবুর্চি',
            'en_name' => 'Cook',
            'short_name' => '',
            'pay_scale' => 'Grade-20',
            'status' => 'active',
            'created_by' => 2,
            'updated_by' => 2,
            'created_at' => '2021-01-20 10:40:20',
            'updated_at' => '2021-01-20 10:40:20',
            'deleted_at' => '2021-01-20 10:40:20',
        ),
        85 => 
        array (
            'id' => 86,
            'serial' => 86,
            'bn_name' => 'সহকারী বাবুর্চি',
            'en_name' => 'Assistant Cook ',
            'short_name' => '',
            'pay_scale' => 'Grade-20',
            'status' => 'active',
            'created_by' => 2,
            'updated_by' => 2,
            'created_at' => '2021-01-20 10:40:20',
            'updated_at' => '2021-01-20 10:40:20',
            'deleted_at' => '2021-01-20 10:40:20',
        ),
        86 => 
        array (
            'id' => 87,
            'serial' => 87,
            'bn_name' => 'মালী ',
            'en_name' => 'Gardener',
            'short_name' => '',
            'pay_scale' => 'Grade-20',
            'status' => 'active',
            'created_by' => 2,
            'updated_by' => 2,
            'created_at' => '2021-01-20 10:40:20',
            'updated_at' => '2021-01-20 10:40:20',
            'deleted_at' => '2021-01-20 10:40:20',
        ),
        87 => 
        array (
            'id' => 88,
            'serial' => 88,
            'bn_name' => 'নাপিত ',
            'en_name' => 'Barbar ',
            'short_name' => '',
            'pay_scale' => 'Grade-20',
            'status' => 'active',
            'created_by' => 2,
            'updated_by' => 2,
            'created_at' => '2021-01-20 10:40:20',
            'updated_at' => '2021-01-20 10:40:20',
            'deleted_at' => '2021-01-20 10:40:20',
        ),
        88 => 
        array (
            'id' => 89,
            'serial' => 89,
            'bn_name' => 'মুচি ',
            'en_name' => 'Cobler ',
            'short_name' => '',
            'pay_scale' => 'Grade-20',
            'status' => 'active',
            'created_by' => 2,
            'updated_by' => 2,
            'created_at' => '2021-01-20 10:40:20',
            'updated_at' => '2021-01-20 10:40:20',
            'deleted_at' => '2021-01-20 10:40:20',
        ),
        89 => 
        array (
            'id' => 90,
            'serial' => 90,
            'bn_name' => 'ধোপা ',
            'en_name' => 'Washerman',
            'short_name' => '',
            'pay_scale' => 'Grade-20',
            'status' => 'active',
            'created_by' => 2,
            'updated_by' => 2,
            'created_at' => '2021-01-20 10:40:20',
            'updated_at' => '2021-01-20 10:40:20',
            'deleted_at' => '2021-01-20 10:40:20',
        ),
        90 => 
        array (
            'id' => 91,
            'serial' => 91,
            'bn_name' => 'পরিচ্ছন্নতাকর্মী ',
            'en_name' => 'Sweaper ',
            'short_name' => '',
            'pay_scale' => 'Grade-20',
            'status' => 'active',
            'created_by' => 2,
            'updated_by' => 2,
            'created_at' => '2021-01-20 10:40:20',
            'updated_at' => '2021-01-20 10:40:20',
            'deleted_at' => '2021-01-20 10:40:20',
        ),
    ));
        
        
    }
}