<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class InstituteSeeder extends Seeder
{
    public function run()
    {
        DB::table('institutes')->truncate();

        $graduation_institutes = [
            ['name' => "Bangabandhu Sheikh Mujibur Rahman Science and Technology University", 'type' => 'Graduation'],
            ['name' => "Bangabandhu Sheikh Mujib Medical University", 'type' => 'Graduation'],
            ['name' => "Bangabandhu Sheikh Mujibur Rahman Agricultural University", 'type' => 'Graduation'],
            ['name' => "Bangladesh Agricultural University,Mymensingh", 'type' => 'Graduation'],
            ['name' => "Bangladesh Open University", 'type' => 'Graduation'],
            ['name' => "Bangladesh University of Engineering &amp; Technology", 'type' => 'Graduation'],
            ['name' => "Bangladesh University of Professionals", 'type' => 'Graduation'],
            ['name' => "Chattogram University of Engineering &amp; Technology", 'type' => 'Graduation'],
            ['name' => "Chattogram Veterinary and Animal Sciences University", 'type' => 'Graduation'],
            ['name' => "Comilla University", 'type' => 'Graduation'],
            ['name' => "Dhaka University", 'type' => 'Graduation'],
            ['name' => "Dhaka University of Engineering &amp; Technology", 'type' => 'Graduation'],
            ['name' => "Hajee Mohammad Danesh Science &amp; Technology University", 'type' => 'Graduation'],
            ['name' => "Islamic University, Kushtia", 'type' => 'Graduation'],
            ['name' => "Jagannath University", 'type' => 'Graduation'],
            ['name' => "Jahangirnagar University", 'type' => 'Graduation'],
            ['name' => "Jatiya Kabi Kazi Nazrul Islam University", 'type' => 'Graduation'],
            ['name' => "Jessore Science &amp; Technology University", 'type' => 'Graduation'],
            ['name' => "Khulna University", 'type' => 'Graduation'],
            ['name' => "Khulna University of Engineering and Technology", 'type' => 'Graduation'],
            ['name' => "Mawlana Bhashani Science &amp; Technology University", 'type' => 'Graduation'],
            ['name' => "National University", 'type' => 'Graduation'],
            ['name' => "Noakhali Science &amp; Technology University", 'type' => 'Graduation'],
            ['name' => "Pabna University of Science and Technology", 'type' => 'Graduation'],
            ['name' => "Patuakhali Science And Technology University", 'type' => 'Graduation'],
            ['name' => "Rajshahi University", 'type' => 'Graduation'],
            ['name' => "Rajshahi University of Engineering &amp; Technology", 'type' => 'Graduation'],
            ['name' => "Rangpur University", 'type' => 'Graduation'],
            ['name' => "Shahjalal University of Science &amp; Technology", 'type' => 'Graduation'],
            ['name' => "Sher-e-Bangla Agricultural University", 'type' => 'Graduation'],
            ['name' => "Sylhet Agricultural University", 'type' => 'Graduation'],
            ['name' => "University of Chittagong", 'type' => 'Graduation'],
            ['name' => "Faridpur Engineering College", 'type' => 'Graduation'],
            ['name' => "Mymensingh Engineering College", 'type' => 'Graduation'],
            ['name' => "Sylhet Engineering College", 'type' => 'Graduation'],
            ['name' => "Barishal Engineering College", 'type' => 'Graduation'],
            ['name' => "Ahsanullah University of Science and Technology", 'type' => 'Graduation'],
            ['name' => "America Bangladesh University", 'type' => 'Graduation'],
            ['name' => "American International University Bangladesh", 'type' => 'Graduation'],
            ['name' => "ASA University Bangladesh", 'type' => 'Graduation'],
            ['name' => "Asian University of Bangladesh", 'type' => 'Graduation'],
            ['name' => "Atish Dipankar University of Science &amp; Technology", 'type' => 'Graduation'],
            ['name' => "Bangladesh Islami University", 'type' => 'Graduation'],
            ['name' => "Bangladesh University", 'type' => 'Graduation'],
            ['name' => "Bangladesh University of Business &amp; Technology (BUBT)", 'type' => 'Graduation'],
            ['name' => "BGC Trust University Bangladesh, Chittagong", 'type' => 'Graduation'],
            ['name' => "BRAC University", 'type' => 'Graduation'],
            ['name' => "Central Women's University", 'type' => 'Graduation'],
            ['name' => "City University", 'type' => 'Graduation'],
            ['name' => "Daffodil International University", 'type' => 'Graduation'],
            ['name' => "Darul Ihsan University", 'type' => 'Graduation'],
            ['name' => "Dhaka International University", 'type' => 'Graduation'],
            ['name' => "East Delta University , Chittagong", 'type' => 'Graduation'],
            ['name' => "East West University", 'type' => 'Graduation'],
            ['name' => "Eastern University", 'type' => 'Graduation'],
            ['name' => "Gono Bishwabidyalay", 'type' => 'Graduation'],
            ['name' => "Green University of Bangladesh", 'type' => 'Graduation'],
            ['name' => "IBAIS University", 'type' => 'Graduation'],
            ['name' => "Independent University, Bangladesh", 'type' => 'Graduation'],
            ['name' => "International Islamic University, Chittagong", 'type' => 'Graduation'],
            ['name' => "International University of Business Agriculture &amp; Technology", 'type' => 'Graduation'],
            ['name' => "Leading University, Sylhet", 'type' => 'Graduation'],
            ['name' => "Manarat International University", 'type' => 'Graduation'],
            ['name' => "Metropolitan University, Sylhet", 'type' => 'Graduation'],
            ['name' => "North South University", 'type' => 'Graduation'],
            ['name' => "Northern University Bangladesh", 'type' => 'Graduation'],
            ['name' => "Premier University, Chittagong", 'type' => 'Graduation'],
            ['name' => "Presidency University", 'type' => 'Graduation'],
            ['name' => "Prime University", 'type' => 'Graduation'],
            ['name' => "Primeasia University", 'type' => 'Graduation'],
            ['name' => "Queens University", 'type' => 'Graduation'],
            ['name' => "Royal University of Dhaka", 'type' => 'Graduation'],
            ['name' => "Shanto Mariam University of Creative Technology", 'type' => 'Graduation'],
            ['name' => "Southeast University", 'type' => 'Graduation'],
            ['name' => "Southern University of Bangladesh , Chittagong", 'type' => 'Graduation'],
            ['name' => "Stamford University, Bangladesh", 'type' => 'Graduation'],
            ['name' => "State University Of Bangladesh", 'type' => 'Graduation'],
            ['name' => "Sylhet International University, Sylhet", 'type' => 'Graduation'],
            ['name' => "The Millenium University", 'type' => 'Graduation'],
            ['name' => "The Peoples University of Bangladesh", 'type' => 'Graduation'],
            ['name' => "The University of Asia Pacific", 'type' => 'Graduation'],
            ['name' => "United International University", 'type' => 'Graduation'],
            ['name' => "University of Development Alternative", 'type' => 'Graduation'],
            ['name' => "University of Information Technology &amp; Sciences", 'type' => 'Graduation'],
            ['name' => "University of Liberal Arts Bangladesh", 'type' => 'Graduation'],
            ['name' => "University of Science &amp; Technology, Chittagong", 'type' => 'Graduation'],
            ['name' => "University of South Asia", 'type' => 'Graduation'],
            ['name' => "Uttara University", 'type' => 'Graduation'],
            ['name' => "Victoria University of Bangladesh", 'type' => 'Graduation'],
            ['name' => "World University of Bangladesh", 'type' => 'Graduation'],
            ['name' => "Asian University for Women", 'type' => 'Graduation'],
            ['name' => "Islamic University of Technology", 'type' => 'Graduation'],
            ['name' => "South Asian University", 'type' => 'Graduation'],
            ['name' => "Dhaka Medical College", 'type' => 'Graduation'],
            ['name' => "Sir Salimullah Medical College", 'type' => 'Graduation'],
            ['name' => "Mymensingh Medical College", 'type' => 'Graduation'],
            ['name' => "Chattogram Medical College", 'type' => 'Graduation'],
            ['name' => "Rajshahi Medical College", 'type' => 'Graduation'],
            ['name' => "MAG Osmani Medical College", 'type' => 'Graduation'],
            ['name' => "Sher-E-Bangla Medical College", 'type' => 'Graduation'],
            ['name' => "Rangpur Medical College", 'type' => 'Graduation'],
            ['name' => "Comilla Medical College", 'type' => 'Graduation'],
            ['name' => "Khulna Medical College", 'type' => 'Graduation'],
            ['name' => "Shaheed Ziaur Rahman Medical College", 'type' => 'Graduation'],
            ['name' => "Dinajpur Medical College", 'type' => 'Graduation'],
            ['name' => "Faridpur Medical College", 'type' => 'Graduation'],
            ['name' => "Shaheed Suhrawardy Medical College", 'type' => 'Graduation'],
            ['name' => "Pabna Medical College", 'type' => 'Graduation'],
            ['name' => "Noakhali Medical College", 'type' => 'Graduation'],
            ['name' => "Cox's Bazar Medical College", 'type' => 'Graduation'],
            ['name' => "Jessore Medical College", 'type' => 'Graduation'],
            ['name' => "Shaheed Nazrul Islam Medical College", 'type' => 'Graduation'],
            ['name' => "Kushtia Medical College", 'type' => 'Graduation'],
            ['name' => "Satkhira Medical College", 'type' => 'Graduation'],
            ['name' => "Sheikh Sayera Khatun Medical College, Gopalganj", 'type' => 'Graduation'],
            ['name' => "Feni Medical College,Feni", 'type' => 'Graduation'],
            ['name' => "Gono Bishwabidyalay, Savar, Dhaka", 'type' => 'Graduation'],
            ['name' => "Ad-din Womens Medical College, Dhaka", 'type' => 'Graduation'],
            ['name' => "Anwer Khan Modern Medical College, Dhaka", 'type' => 'Graduation'],
            ['name' => "Bangladesh Medical College", 'type' => 'Graduation'],
            ['name' => "Jalalabad Rageb-Rabeya Medical College,Sylhet", 'type' => 'Graduation'],
            ['name' => "BGC Trust Medical College, Chittagong", 'type' => 'Graduation'],
            ['name' => "Central Medical College, Comilla", 'type' => 'Graduation'],
            ['name' => "Chottagram Ma-O-Shishu Hospital Medical College", 'type' => 'Graduation'],
            ['name' => "Community Based Medical College (cbmc), Mymensingh", 'type' => 'Graduation'],
            ['name' => "Community Medical College, Dhaka", 'type' => 'Graduation'],
            ['name' => "Delta Medical College, Dhaka", 'type' => 'Graduation'],
            ['name' => "Dhaka National Medical College", 'type' => 'Graduation'],
            ['name' => "Durra Samad Rahman Red Crescent Women`s Medical College, Sylhet", 'type' => 'Graduation'],
            ['name' => "Eastern Medical College, Comilla", 'type' => 'Graduation'],
            ['name' => "Enam Medical College, Savar, Dhaka", 'type' => 'Graduation'],
            ['name' => "Sylhet Women`s Medical College, Sylhet", 'type' => 'Graduation'],
            ['name' => "Green Life Medical College,Dhaka", 'type' => 'Graduation'],
            ['name' => "Holy Family Red Crescent Medical College, Dhaka", 'type' => 'Graduation'],
            ['name' => "Ibrahim Medical College, Dhaka", 'type' => 'Graduation'],
            ['name' => "Ibn Sina Medical College, Dhaka", 'type' => 'Graduation'],
            ['name' => "International Medical College, Gazipur", 'type' => 'Graduation'],
            ['name' => "Islami Bank Medical College, Rajshahi", 'type' => 'Graduation'],
            ['name' => "Jahurul Islam Medical College, Kishoregonj", 'type' => 'Graduation'],
            ['name' => "Jalalabad Ragib-Rabeya Medical College Sylhet", 'type' => 'Graduation'],
            ['name' => "Khawja Yunus Ali Medical College, Sirajganj", 'type' => 'Graduation'],
            ['name' => "Kumudini Medical College, Tangail", 'type' => 'Graduation'],
            ['name' => "Labaid Medical College[6] Dhanmondi, Dhaka", 'type' => 'Graduation'],
            ['name' => "Maulana Bhasani Medical College", 'type' => 'Graduation'],
            ['name' => "Medical College for Women and Hospital, Dhaka", 'type' => 'Graduation'],
            ['name' => "Nightingale Medical College, Dhaka", 'type' => 'Graduation'],
            ['name' => "North Bengal Medical College, Sirajganj", 'type' => 'Graduation'],
            ['name' => "North East Medical College, Sylhet", 'type' => 'Graduation'],
            ['name' => "Northern International Medical College, Dhaka", 'type' => 'Graduation'],
            ['name' => "Northern Private Medical College, Rangpur", 'type' => 'Graduation'],
            ['name' => "Popular Medical College &amp; Hospital, Dhaka", 'type' => 'Graduation'],
            ['name' => "Prime Medical College, Rangpur", 'type' => 'Graduation'],
            ['name' => "Rangpur Community Hospital Medical College", 'type' => 'Graduation'],
            ['name' => "Sahabuddin Medical College and Hospital", 'type' => 'Graduation'],
            ['name' => "Samaj Vittik Medical College, Mirzanagar, Savar", 'type' => 'Graduation'],
            ['name' => "Shahabuddin Medical College, Dhaka", 'type' => 'Graduation'],
            ['name' => "Z. H. Sikder Women`s Medical College", 'type' => 'Graduation'],
            ['name' => "Southern Medical College, Chittagong", 'type' => 'Graduation'],
            ['name' => "Tairunnessa Memorial Medical College, Gazipur", 'type' => 'Graduation'],
            ['name' => "TMSS Medical College,Bogra", 'type' => 'Graduation'],
            ['name' => "University Of Science and Technology Chittagong. IAMS", 'type' => 'Graduation'],
            ['name' => "Uttara Adhunik Medical College,Dhaka", 'type' => 'Graduation'],
            ['name' => "Military Institute of Science and Technology (MIST)", 'type' => 'Graduation'],
            ['name' => "Sonargaon University", 'type' => 'Graduation'],
            ['name' => "Anwer Khan Modern University", 'type' => 'Graduation'],
            ['name' => "Bandarban University", 'type' => 'Graduation'],
            ['name' => "Bangabandhu Sheikh Mujibur Rahman Digital University", 'type' => 'Graduation'],
            ['name' => "Bangabandhu Sheikh Mujibur Rahman Maritime University", 'type' => 'Graduation'],
            ['name' => "Bangabandhu Sheikh Mujibur Rahman Science &amp; Technology University", 'type' => 'Graduation'],
            ['name' => "Bangamata Sheikh Fojilatunnesa Mujib Science and Technology University", 'type' => 'Graduation'],
            ['name' => "Bangladesh Agricultural University", 'type' => 'Graduation'],
            ['name' => "Bangladesh Army International University of Science &amp; Technology(BAIUST) ,Comilla", 'type' => 'Graduation'],
            ['name' => "Bangladesh Army University of Engineering and Technology (BAUET), Qadirabad", 'type' => 'Graduation'],
            ['name' => "Bangladesh Army University of Science and Technology(BAUST), Saidpur", 'type' => 'Graduation'],
            ['name' => "Bangladesh University of Health Sciences", 'type' => 'Graduation'],
            ['name' => "Bangladesh University of Textiles", 'type' => 'Graduation'],
            ['name' => "Barishal University", 'type' => 'Graduation'],
            ['name' => "Begum Rokeya University", 'type' => 'Graduation'],
            ['name' => "BGMEA University of Fashion &amp; Technology(BUFT)", 'type' => 'Graduation'],
            ['name' => "Canadian University of Bangladesh", 'type' => 'Graduation'],
            ['name' => "CCN University of Science &amp; Technology", 'type' => 'Graduation'],
            ['name' => "Chattogram Independent University", 'type' => 'Graduation'],
            ['name' => "Chattogram Medical University", 'type' => 'Graduation'],
            ['name' => "Cox's Bazar International University", 'type' => 'Graduation'],
            ['name' => "East Delta University", 'type' => 'Graduation'],
            ['name' => "European University of Bangladesh", 'type' => 'Graduation'],
            ['name' => "Exim Bank Agricultural University, Bangladesh", 'type' => 'Graduation'],
            ['name' => "Fareast International University", 'type' => 'Graduation'],
            ['name' => "Feni University", 'type' => 'Graduation'],
            ['name' => "First Capital University of Bangladesh", 'type' => 'Graduation'],
            ['name' => "German University Bangladesh", 'type' => 'Graduation'],
            ['name' => "Global University Bangladesh", 'type' => 'Graduation'],
            ['name' => "Hamdard University Bangladesh", 'type' => 'Graduation'],
            ['name' => "Ishakha International University, Bangladesh", 'type' => 'Graduation'],
            ['name' => "Islamic Arabic University", 'type' => 'Graduation'],
            ['name' => "Islamic University", 'type' => 'Graduation'],
            ['name' => "Jessore University of Science &amp; Technology", 'type' => 'Graduation'],
            ['name' => "Khulna Agricultural University", 'type' => 'Graduation'],
            ['name' => "Khwaja Yunus Ali University", 'type' => 'Graduation'],
            ['name' => "N.P.I University of Bangladesh", 'type' => 'Graduation'],
            ['name' => "North Bengal International University", 'type' => 'Graduation'],
            ['name' => "North East University Bangladesh", 'type' => 'Graduation'],
            ['name' => "North Western University<", 'type' => 'Graduation'],
            ['name' => "Northern University of Business &amp; Technology, Khulna", 'type' => 'Graduation'],
            ['name' => "Notre Dame University Bangladesh", 'type' => 'Graduation'],
            ['name' => "Port City International University", 'type' => 'Graduation'],
            ['name' => "Rabindra Maitree University, Kushtia", 'type' => 'Graduation'],
            ['name' => "Rabindra University, Bangladesh", 'type' => 'Graduation'],
            ['name' => "Rajshahi Medical University", 'type' => 'Graduation'],
            ['name' => "Rajshahi Science &amp; Technology University (RSTU), Natore", 'type' => 'Graduation'],
            ['name' => "Ranada Prasad Shaha University", 'type' => 'Graduation'],
            ['name' => "Rangamati Science and Technology University", 'type' => 'Graduation'],
            ['name' => "Sheikh Fazilatunnesa Mujib University", 'type' => 'Graduation'],
            ['name' => "Sheikh Hasina University", 'type' => 'Graduation'],
            ['name' => "Sonargaon University", 'type' => 'Graduation'],
            ['name' => "Sylhet Medical University", 'type' => 'Graduation'],
            ['name' => "The International University of Scholars", 'type' => 'Graduation'],
            ['name' => "Times University, Bangladesh", 'type' => 'Graduation'],
            ['name' => "University of Creative Technology, Chittagong", 'type' => 'Graduation'],
            ['name' => "University of Global Village", 'type' => 'Graduation'],
            ['name' => "Varendra University", 'type' => 'Graduation'],
            ['name' => "Z.H Sikder University of Science &amp; Technology", 'type' => 'Graduation'],
            ['name' => "Z.N.R.F. University of Management Sciences", 'type' => 'Graduation'],
            ['name' => "Others", 'type' => 'Graduation'],
        ];

        $masters_institutes = [
            ['name' => "Bangabandhu Sheikh Mujibur Rahman Science and Technology University", 'type' => 'Masters'],
            ['name' => "Bangabandhu Sheikh Mujib Medical University", 'type' => 'Masters'],
            ['name' => "Bangabandhu Sheikh Mujibur Rahman Agricultural University", 'type' => 'Masters'],
            ['name' => "Bangladesh Agricultural University,Mymensingh", 'type' => 'Masters'],
            ['name' => "Bangladesh Open University", 'type' => 'Masters'],
            ['name' => "Bangladesh University of Engineering &amp; Technology", 'type' => 'Masters'],
            ['name' => "Bangladesh University of Professionals", 'type' => 'Masters'],
            ['name' => "Chattogram University of Engineering &amp; Technology", 'type' => 'Masters'],
            ['name' => "Chattogram Veterinary and Animal Sciences University", 'type' => 'Masters'],
            ['name' => "Comilla University", 'type' => 'Masters'],
            ['name' => "Dhaka University", 'type' => 'Masters'],
            ['name' => "Dhaka University of Engineering &amp; Technology", 'type' => 'Masters'],
            ['name' => "Hajee Mohammad Danesh Science &amp; Technology University", 'type' => 'Masters'],
            ['name' => "Islamic University, Kushtia", 'type' => 'Masters'],
            ['name' => "Jagannath University", 'type' => 'Masters'],
            ['name' => "Jahangirnagar University", 'type' => 'Masters'],
            ['name' => "Jatiya Kabi Kazi Nazrul Islam University", 'type' => 'Masters'],
            ['name' => "Jessore Science &amp; Technology University", 'type' => 'Masters'],
            ['name' => "Khulna University", 'type' => 'Masters'],
            ['name' => "Khulna University of Engineering and Technology", 'type' => 'Masters'],
            ['name' => "Mawlana Bhashani Science &amp; Technology University", 'type' => 'Masters'],
            ['name' => "National University", 'type' => 'Masters'],
            ['name' => "Noakhali Science &amp; Technology University", 'type' => 'Masters'],
            ['name' => "Pabna University of Science and Technology", 'type' => 'Masters'],
            ['name' => "Patuakhali Science And Technology University", 'type' => 'Masters'],
            ['name' => "Rajshahi University", 'type' => 'Masters'],
            ['name' => "Rajshahi University of Engineering &amp; Technology", 'type' => 'Masters'],
            ['name' => "Rangpur University", 'type' => 'Masters'],
            ['name' => "Shahjalal University of Science &amp; Technology", 'type' => 'Masters'],
            ['name' => "Sher-e-Bangla Agricultural University", 'type' => 'Masters'],
            ['name' => "Sylhet Agricultural University", 'type' => 'Masters'],
            ['name' => "University of Chittagong", 'type' => 'Masters'],
            ['name' => "Faridpur Engineering College", 'type' => 'Masters'],
            ['name' => "Mymensingh Engineering College", 'type' => 'Masters'],
            ['name' => "Sylhet Engineering College", 'type' => 'Masters'],
            ['name' => "Barishal Engineering College", 'type' => 'Masters'],
            ['name' => "Ahsanullah University of Science and Technology", 'type' => 'Masters'],
            ['name' => "America Bangladesh University", 'type' => 'Masters'],
            ['name' => "American International University Bangladesh", 'type' => 'Masters'],
            ['name' => "ASA University Bangladesh", 'type' => 'Masters'],
            ['name' => "Asian University of Bangladesh", 'type' => 'Masters'],
            ['name' => "Atish Dipankar University of Science &amp; Technology", 'type' => 'Masters'],
            ['name' => "Bangladesh Islami University", 'type' => 'Masters'],
            ['name' => "Bangladesh University", 'type' => 'Masters'],
            ['name' => "Bangladesh University of Business &amp; Technology (BUBT)", 'type' => 'Masters'],
            ['name' => "BGC Trust University Bangladesh, Chittagong", 'type' => 'Masters'],
            ['name' => "BRAC University", 'type' => 'Masters'],
            ['name' => "Central Women's University", 'type' => 'Masters'],
            ['name' => "City University", 'type' => 'Masters'],
            ['name' => "Daffodil International University", 'type' => 'Masters'],
            ['name' => "Darul Ihsan University", 'type' => 'Masters'],
            ['name' => "Dhaka International University", 'type' => 'Masters'],
            ['name' => "East Delta University , Chittagong", 'type' => 'Masters'],
            ['name' => "East West University", 'type' => 'Masters'],
            ['name' => "Eastern University", 'type' => 'Masters'],
            ['name' => "Gono Bishwabidyalay", 'type' => 'Masters'],
            ['name' => "Green University of Bangladesh", 'type' => 'Masters'],
            ['name' => "IBAIS University", 'type' => 'Masters'],
            ['name' => "Independent University, Bangladesh", 'type' => 'Masters'],
            ['name' => "International Islamic University, Chittagong", 'type' => 'Masters'],
            ['name' => "International University of Business Agriculture &amp; Technology", 'type' => 'Masters'],
            ['name' => "Leading University, Sylhet", 'type' => 'Masters'],
            ['name' => "Manarat International University", 'type' => 'Masters'],
            ['name' => "Metropolitan University, Sylhet", 'type' => 'Masters'],
            ['name' => "North South University", 'type' => 'Masters'],
            ['name' => "Northern University Bangladesh", 'type' => 'Masters'],
            ['name' => "Premier University, Chittagong", 'type' => 'Masters'],
            ['name' => "Presidency University", 'type' => 'Masters'],
            ['name' => "Prime University", 'type' => 'Masters'],
            ['name' => "Primeasia University", 'type' => 'Masters'],
            ['name' => "Queens University", 'type' => 'Masters'],
            ['name' => "Royal University of Dhaka", 'type' => 'Masters'],
            ['name' => "Shanto Mariam University of Creative Technology", 'type' => 'Masters'],
            ['name' => "Southeast University", 'type' => 'Masters'],
            ['name' => "Southern University of Bangladesh , Chittagong", 'type' => 'Masters'],
            ['name' => "Stamford University, Bangladesh", 'type' => 'Masters'],
            ['name' => "State University Of Bangladesh", 'type' => 'Masters'],
            ['name' => "Sylhet International University, Sylhet", 'type' => 'Masters'],
            ['name' => "The Millenium University", 'type' => 'Masters'],
            ['name' => "The Peoples University of Bangladesh", 'type' => 'Masters'],
            ['name' => "The University of Asia Pacific", 'type' => 'Masters'],
            ['name' => "United International University", 'type' => 'Masters'],
            ['name' => "University of Development Alternative", 'type' => 'Masters'],
            ['name' => "University of Information Technology &amp; Sciences", 'type' => 'Masters'],
            ['name' => "University of Liberal Arts Bangladesh", 'type' => 'Masters'],
            ['name' => "University of Science &amp; Technology, Chittagong", 'type' => 'Masters'],
            ['name' => "University of South Asia", 'type' => 'Masters'],
            ['name' => "Uttara University", 'type' => 'Masters'],
            ['name' => "Victoria University of Bangladesh", 'type' => 'Masters'],
            ['name' => "World University of Bangladesh", 'type' => 'Masters'],
            ['name' => "Asian University for Women", 'type' => 'Masters'],
            ['name' => "Islamic University of Technology", 'type' => 'Masters'],
            ['name' => "South Asian University", 'type' => 'Masters'],
            ['name' => "Dhaka Medical College", 'type' => 'Masters'],
            ['name' => "Sir Salimullah Medical College", 'type' => 'Masters'],
            ['name' => "Mymensingh Medical College", 'type' => 'Masters'],
            ['name' => "Chattogram Medical College", 'type' => 'Masters'],
            ['name' => "Rajshahi Medical College", 'type' => 'Masters'],
            ['name' => "MAG Osmani Medical College", 'type' => 'Masters'],
            ['name' => "Sher-E-Bangla Medical College", 'type' => 'Masters'],
            ['name' => "Rangpur Medical College", 'type' => 'Masters'],
            ['name' => "Comilla Medical College", 'type' => 'Masters'],
            ['name' => "Khulna Medical College", 'type' => 'Masters'],
            ['name' => "Shaheed Ziaur Rahman Medical College", 'type' => 'Masters'],
            ['name' => "Dinajpur Medical College", 'type' => 'Masters'],
            ['name' => "Faridpur Medical College", 'type' => 'Masters'],
            ['name' => "Shaheed Suhrawardy Medical College", 'type' => 'Masters'],
            ['name' => "Pabna Medical College", 'type' => 'Masters'],
            ['name' => "Noakhali Medical College", 'type' => 'Masters'],
            ['name' => "Cox's Bazar Medical College", 'type' => 'Masters'],
            ['name' => "Jessore Medical College", 'type' => 'Masters'],
            ['name' => "Shaheed Nazrul Islam Medical College", 'type' => 'Masters'],
            ['name' => "Kushtia Medical College", 'type' => 'Masters'],
            ['name' => "Satkhira Medical College", 'type' => 'Masters'],
            ['name' => "Sheikh Sayera Khatun Medical College, Gopalganj", 'type' => 'Masters'],
            ['name' => "Feni Medical College,Feni", 'type' => 'Masters'],
            ['name' => "Gono Bishwabidyalay, Savar, Dhaka", 'type' => 'Masters'],
            ['name' => "Ad-din Womens Medical College, Dhaka", 'type' => 'Masters'],
            ['name' => "Anwer Khan Modern Medical College, Dhaka", 'type' => 'Masters'],
            ['name' => "Bangladesh Medical College", 'type' => 'Masters'],
            ['name' => "Jalalabad Rageb-Rabeya Medical College,Sylhet", 'type' => 'Masters'],
            ['name' => "BGC Trust Medical College, Chittagong", 'type' => 'Masters'],
            ['name' => "Central Medical College, Comilla", 'type' => 'Masters'],
            ['name' => "Chottagram Ma-O-Shishu Hospital Medical College", 'type' => 'Masters'],
            ['name' => "Community Based Medical College (cbmc), Mymensingh", 'type' => 'Masters'],
            ['name' => "Community Medical College, Dhaka", 'type' => 'Masters'],
            ['name' => "Delta Medical College, Dhaka", 'type' => 'Masters'],
            ['name' => "Dhaka National Medical College", 'type' => 'Masters'],
            ['name' => "Durra Samad Rahman Red Crescent Women`s Medical College, Sylhet", 'type' => 'Masters'],
            ['name' => "Eastern Medical College, Comilla", 'type' => 'Masters'],
            ['name' => "Enam Medical College, Savar, Dhaka", 'type' => 'Masters'],
            ['name' => "Sylhet Women`s Medical College, Sylhet", 'type' => 'Masters'],
            ['name' => "Green Life Medical College,Dhaka", 'type' => 'Masters'],
            ['name' => "Holy Family Red Crescent Medical College, Dhaka", 'type' => 'Masters'],
            ['name' => "Ibrahim Medical College, Dhaka", 'type' => 'Masters'],
            ['name' => "Ibn Sina Medical College, Dhaka", 'type' => 'Masters'],
            ['name' => "International Medical College, Gazipur", 'type' => 'Masters'],
            ['name' => "Islami Bank Medical College, Rajshahi", 'type' => 'Masters'],
            ['name' => "Jahurul Islam Medical College, Kishoregonj", 'type' => 'Masters'],
            ['name' => "Jalalabad Ragib-Rabeya Medical College Sylhet", 'type' => 'Masters'],
            ['name' => "Khawja Yunus Ali Medical College, Sirajganj", 'type' => 'Masters'],
            ['name' => "Kumudini Medical College, Tangail", 'type' => 'Masters'],
            ['name' => "Labaid Medical College[6] Dhanmondi, Dhaka", 'type' => 'Masters'],
            ['name' => "Maulana Bhasani Medical College", 'type' => 'Masters'],
            ['name' => "Medical College for Women and Hospital, Dhaka", 'type' => 'Masters'],
            ['name' => "Nightingale Medical College, Dhaka", 'type' => 'Masters'],
            ['name' => "North Bengal Medical College, Sirajganj", 'type' => 'Masters'],
            ['name' => "North East Medical College, Sylhet", 'type' => 'Masters'],
            ['name' => "Northern International Medical College, Dhaka", 'type' => 'Masters'],
            ['name' => "Northern Private Medical College, Rangpur", 'type' => 'Masters'],
            ['name' => "Popular Medical College &amp; Hospital, Dhaka", 'type' => 'Masters'],
            ['name' => "Prime Medical College, Rangpur", 'type' => 'Masters'],
            ['name' => "Rangpur Community Hospital Medical College", 'type' => 'Masters'],
            ['name' => "Sahabuddin Medical College and Hospital", 'type' => 'Masters'],
            ['name' => "Samaj Vittik Medical College, Mirzanagar, Savar", 'type' => 'Masters'],
            ['name' => "Shahabuddin Medical College, Dhaka", 'type' => 'Masters'],
            ['name' => "Z. H. Sikder Women`s Medical College", 'type' => 'Masters'],
            ['name' => "Southern Medical College, Chittagong", 'type' => 'Masters'],
            ['name' => "Tairunnessa Memorial Medical College, Gazipur", 'type' => 'Masters'],
            ['name' => "TMSS Medical College,Bogra", 'type' => 'Masters'],
            ['name' => "University Of Science and Technology Chittagong. IAMS", 'type' => 'Masters'],
            ['name' => "Uttara Adhunik Medical College,Dhaka", 'type' => 'Masters'],
            ['name' => "Military Institute of Science and Technology (MIST)", 'type' => 'Masters'],
            ['name' => "Sonargaon University", 'type' => 'Masters'],
            ['name' => "Anwer Khan Modern University", 'type' => 'Masters'],
            ['name' => "Bandarban University", 'type' => 'Masters'],
            ['name' => "Bangabandhu Sheikh Mujibur Rahman Digital University", 'type' => 'Masters'],
            ['name' => "Bangabandhu Sheikh Mujibur Rahman Maritime University", 'type' => 'Masters'],
            ['name' => "Bangabandhu Sheikh Mujibur Rahman Science &amp; Technology University", 'type' => 'Masters'],
            ['name' => "Bangamata Sheikh Fojilatunnesa Mujib Science and Technology University", 'type' => 'Masters'],
            ['name' => "Bangladesh Agricultural University", 'type' => 'Masters'],
            ['name' => "Bangladesh Army International University of Science &amp; Technology(BAIUST) ,Comilla", 'type' => 'Masters'],
            ['name' => "Bangladesh Army University of Engineering and Technology (BAUET), Qadirabad", 'type' => 'Masters'],
            ['name' => "Bangladesh Army University of Science and Technology(BAUST), Saidpur", 'type' => 'Masters'],
            ['name' => "Bangladesh University of Health Sciences", 'type' => 'Masters'],
            ['name' => "Bangladesh University of Textiles", 'type' => 'Masters'],
            ['name' => "Barishal University", 'type' => 'Masters'],
            ['name' => "Begum Rokeya University", 'type' => 'Masters'],
            ['name' => "BGMEA University of Fashion &amp; Technology(BUFT)", 'type' => 'Masters'],
            ['name' => "Canadian University of Bangladesh", 'type' => 'Masters'],
            ['name' => "CCN University of Science &amp; Technology", 'type' => 'Masters'],
            ['name' => "Chattogram Independent University", 'type' => 'Masters'],
            ['name' => "Chattogram Medical University", 'type' => 'Masters'],
            ['name' => "Cox's Bazar International University", 'type' => 'Masters'],
            ['name' => "East Delta University", 'type' => 'Masters'],
            ['name' => "European University of Bangladesh", 'type' => 'Masters'],
            ['name' => "Exim Bank Agricultural University, Bangladesh", 'type' => 'Masters'],
            ['name' => "Fareast International University", 'type' => 'Masters'],
            ['name' => "Feni University", 'type' => 'Masters'],
            ['name' => "First Capital University of Bangladesh", 'type' => 'Masters'],
            ['name' => "German University Bangladesh", 'type' => 'Masters'],
            ['name' => "Global University Bangladesh", 'type' => 'Masters'],
            ['name' => "Hamdard University Bangladesh", 'type' => 'Masters'],
            ['name' => "Ishakha International University, Bangladesh", 'type' => 'Masters'],
            ['name' => "Islamic Arabic University", 'type' => 'Masters'],
            ['name' => "Islamic University", 'type' => 'Masters'],
            ['name' => "Jessore University of Science &amp; Technology", 'type' => 'Masters'],
            ['name' => "Khulna Agricultural University", 'type' => 'Masters'],
            ['name' => "Khwaja Yunus Ali University", 'type' => 'Masters'],
            ['name' => "N.P.I University of Bangladesh", 'type' => 'Masters'],
            ['name' => "North Bengal International University", 'type' => 'Masters'],
            ['name' => "North East University Bangladesh", 'type' => 'Masters'],
            ['name' => "North Western University<", 'type' => 'Masters'],
            ['name' => "Northern University of Business &amp; Technology, Khulna", 'type' => 'Masters'],
            ['name' => "Notre Dame University Bangladesh", 'type' => 'Masters'],
            ['name' => "Port City International University", 'type' => 'Masters'],
            ['name' => "Rabindra Maitree University, Kushtia", 'type' => 'Masters'],
            ['name' => "Rabindra University, Bangladesh", 'type' => 'Masters'],
            ['name' => "Rajshahi Medical University", 'type' => 'Masters'],
            ['name' => "Rajshahi Science &amp; Technology University (RSTU), Natore", 'type' => 'Masters'],
            ['name' => "Ranada Prasad Shaha University", 'type' => 'Masters'],
            ['name' => "Rangamati Science and Technology University", 'type' => 'Masters'],
            ['name' => "Sheikh Fazilatunnesa Mujib University", 'type' => 'Masters'],
            ['name' => "Sheikh Hasina University", 'type' => 'Masters'],
            ['name' => "Sonargaon University", 'type' => 'Masters'],
            ['name' => "Sylhet Medical University", 'type' => 'Masters'],
            ['name' => "The International University of Scholars", 'type' => 'Masters'],
            ['name' => "Times University, Bangladesh", 'type' => 'Masters'],
            ['name' => "University of Creative Technology, Chittagong", 'type' => 'Masters'],
            ['name' => "University of Global Village", 'type' => 'Masters'],
            ['name' => "Varendra University", 'type' => 'Masters'],
            ['name' => "Z.H Sikder University of Science &amp; Technology", 'type' => 'Masters'],
            ['name' => "Z.N.R.F. University of Management Sciences", 'type' => 'Masters'],
            ['name' => "Others", 'type' => 'Masters'],
        ];

        DB::table('institutes')->insert($graduation_institutes);
        DB::table('institutes')->insert($masters_institutes);

    }
}
