<?php

namespace Database\Seeders;

use App\Models\Subject;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class SubjectSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('subjects')->truncate();

        $ssc_subjects = [
            ['name' => 'Science', 'type' => 'SSC'],
            ['name' => 'Humanities', 'type' => 'SSC'],
            ['name' => 'Business Studies', 'type' => 'SSC'],
            ['name' => 'Agriculture Technology', 'type' => 'SSC'],
            ['name' => 'Architecture and Interior Design Technology', 'type' => 'SSC'],
            ['name' => 'Automobile Technology', 'type' => 'SSC'],
            ['name' => 'Civil Technology', 'type' => 'SSC'],
            ['name' => 'Computer Science and Technology', 'type' => 'SSC'],
            ['name' => 'Chemical Technology', 'type' => 'SSC'],
            ['name' => 'Electrical Technology', 'type' => 'SSC'],
            ['name' => 'Data Telecommunication and Network Technology', 'type' => 'SSC'],
            ['name' => 'Electrical and Electronics Technology', 'type' => 'SSC'],
            ['name' => 'Environmental Technology', 'type' => 'SSC'],
            ['name' => 'Instrumentation and Process Control Technology', 'type' => 'SSC'],
            ['name' => 'Mechanical Technology', 'type' => 'SSC'],
            ['name' => 'Mechatronics Technology', 'type' => 'SSC'],
            ['name' => 'Power Technology', 'type' => 'SSC'],
            ['name' => 'Refrigeration and Air Conditioning Technology', 'type' => 'SSC'],
            ['name' => 'Telecommunication Technology', 'type' => 'SSC'],
            ['name' => 'Electronics Technology', 'type' => 'SSC'],
            ['name' => 'Library Science', 'type' => 'SSC'],
            ['name' => 'Survey', 'type' => 'SSC'],
            ['name' => 'General Mechanics', 'type' => 'SSC'],
            ['name' => 'Firm Machinery', 'type' => 'SSC'],
            ['name' => 'Textile Technology', 'type' => 'SSC'],
        ];

        $hsc_subjects = [
            ['name' => 'Science', 'type' => 'HSC'],
            ['name' => 'Humanities', 'type' => 'HSC'],
            ['name' => 'Business Studies', 'type' => 'HSC'],
            ['name' => 'Agriculture Technology', 'type' => 'HSC'],
            ['name' => 'Architecture and Interior Design Technology', 'type' => 'HSC'],
            ['name' => 'Automobile Technology', 'type' => 'HSC'],
            ['name' => 'Civil Technology', 'type' => 'HSC'],
            ['name' => 'Draftsmanship', 'type' => 'HSC'],
            ['name' => 'Computer Science and Engineering Technology', 'type' => 'HSC'],
            ['name' => 'Chemical Technology', 'type' => 'HSC'],
            ['name' => 'Electrical Technology', 'type' => 'HSC'],
            ['name' => 'Data Telecommunication and Network Technology', 'type' => 'HSC'],
            ['name' => 'Electrical and Electronics Technology', 'type' => 'HSC'],
            ['name' => 'Environmental Technology', 'type' => 'HSC'],
            ['name' => 'Information and Communication Technology (ICT)', 'type' => 'HSC'],
            ['name' => 'Instrumentation and Process Control Technology', 'type' => 'HSC'],
            ['name' => 'Mechanical Technology', 'type' => 'HSC'],
            ['name' => 'Mechatronics Technology', 'type' => 'HSC'],
            ['name' => 'Metallurgy', 'type' => 'HSC'],
            ['name' => 'Power Technology', 'type' => 'HSC'],
            ['name' => 'Printing Technology', 'type' => 'HSC'],
            ['name' => 'Refrigeration and Air Conditioning Technology', 'type' => 'HSC'],
            ['name' => 'Telecommunication Technology', 'type' => 'HSC'],
            ['name' => 'Electronics Technology', 'type' => 'HSC'],
            ['name' => 'Library Science', 'type' => 'HSC'],
            ['name' => 'Survey', 'type' => 'HSC'],
            ['name' => 'General Mechanics', 'type' => 'HSC'],
            ['name' => 'Firm Machinery', 'type' => 'HSC'],
            ['name' => 'Textile Technology', 'type' => 'HSC'],
            ['name' => 'Others', 'type' => 'HSC'],
        ];

        $graduation_subjects = [
            ['name' => 'A and B Section of A.M.I.E', 'type' => 'Graduation'],
            ['name' => 'Accounting', 'type' => 'Graduation'],
            ['name' => 'Aeronautical Engineering', 'type' => 'Graduation'],
            ['name' => 'Agr.Co-operative and Marketing', 'type' => 'Graduation'],
            ['name' => 'Agriculture', 'type' => 'Graduation'],
            ['name' => 'Agriculture Chemistry', 'type' => 'Graduation'],
            ['name' => 'Agriculture Co-operatives', 'type' => 'Graduation'],
            ['name' => 'Agriculture Economics', 'type' => 'Graduation'],
            ['name' => 'Agriculture Engineering', 'type' => 'Graduation'],
            ['name' => 'Agriculture Extension', 'type' => 'Graduation'],
            ['name' => 'Agriculture Finance', 'type' => 'Graduation'],
            ['name' => 'Agriculture Marketing', 'type' => 'Graduation'],
            ['name' => 'Agriculture Science', 'type' => 'Graduation'],
            ['name' => 'Agriculture Soil Science', 'type' => 'Graduation'],
            ['name' => 'Agriculture Statistics', 'type' => 'Graduation'],
            ['name' => 'Agriculture Water Management', 'type' => 'Graduation'],
            ['name' => 'Agro Forestry', 'type' => 'Graduation'],
            ['name' => 'Agronomy', 'type' => 'Graduation'],
            ['name' => 'Agronomy and Aquaculture', 'type' => 'Graduation'],
            ['name' => 'Agronomy and Aquaculture Extension', 'type' => 'Graduation'],
            ['name' => 'Akaid', 'type' => 'Graduation'],
            ['name' => 'Anatomology', 'type' => 'Graduation'],
            ['name' => 'Anatomy and Histology', 'type' => 'Graduation'],
            ['name' => 'Animal Breeding and Genetic', 'type' => 'Graduation'],
            ['name' => 'Animal Husbandry', 'type' => 'Graduation'],
            ['name' => 'Animal Nutrition', 'type' => 'Graduation'],
            ['name' => 'Animal Science', 'type' => 'Graduation'],
            ['name' => 'Anthropology', 'type' => 'Graduation'],
            ['name' => 'Applied Chemistry', 'type' => 'Graduation'],
            ['name' => 'Applied Mathematics', 'type' => 'Graduation'],
            ['name' => 'Applied Physics', 'type' => 'Graduation'],
            ['name' => 'Arabic', 'type' => 'Graduation'],
            ['name' => 'Archaeology', 'type' => 'Graduation'],
            ['name' => 'Architecture', 'type' => 'Graduation'],
            ['name' => 'B.A', 'type' => 'Graduation'],
            ['name' => 'B.S.S', 'type' => 'Graduation'],
            ['name' => 'B.Sc', 'type' => 'Graduation'],
            ['name' => 'B.com', 'type' => 'Graduation'],
            ['name' => 'Bangla', 'type' => 'Graduation'],
            ['name' => 'Banking', 'type' => 'Graduation'],
            ['name' => 'Bio-Technology', 'type' => 'Graduation'],
            ['name' => 'Biochemistry', 'type' => 'Graduation'],
            ['name' => 'Botany', 'type' => 'Graduation'],
            ['name' => 'Business Administration', 'type' => 'Graduation'],
            ['name' => 'Business Studies', 'type' => 'Graduation'],
            ['name' => 'Chemical', 'type' => 'Graduation'],
            ['name' => 'Chemistry', 'type' => 'Graduation'],
            ['name' => 'Civil', 'type' => 'Graduation'],
            ['name' => 'Clinical Psychology', 'type' => 'Graduation'],
            ['name' => 'Computer Engineering', 'type' => 'Graduation'],
            ['name' => 'Computer Science', 'type' => 'Graduation'],
            ['name' => 'Computer Science and Engineering', 'type' => 'Graduation'],
            ['name' => 'Computer Science and Information Technology', 'type' => 'Graduation'],
            ['name' => 'Corp Botany', 'type' => 'Graduation'],
            ['name' => 'Criminology and Police Science', 'type' => 'Graduation'],
            ['name' => 'Dairy Science', 'type' => 'Graduation'],
            ['name' => 'Dental Surgery', 'type' => 'Graduation'],
            ['name' => 'Department of Communication Disorders', 'type' => 'Graduation'],
            ['name' => 'Department of Criminology', 'type' => 'Graduation'],
            ['name' => 'Department of Television, Film and Photography', 'type' => 'Graduation'],
            ['name' => 'Department of Women and Gender Studies', 'type' => 'Graduation'],
            ['name' => 'Development Studies', 'type' => 'Graduation'],
            ['name' => 'Doc.of Veterinary Science', 'type' => 'Graduation'],
            ['name' => 'Drama and Music', 'type' => 'Graduation'],
            ['name' => 'Drawing and Printing', 'type' => 'Graduation'],
            ['name' => 'Economics', 'type' => 'Graduation'],
            ['name' => 'Education', 'type' => 'Graduation'],
            ['name' => 'Electrical', 'type' => 'Graduation'],
            ['name' => 'Electrical and Electronics', 'type' => 'Graduation'],
            ['name' => 'Electronic', 'type' => 'Graduation'],
            ['name' => 'Electronics and Communication Engineering', 'type' => 'Graduation'],
            ['name' => 'English', 'type' => 'Graduation'],
            ['name' => 'Environmental Engineering', 'type' => 'Graduation'],
            ['name' => 'Environmental science', 'type' => 'Graduation'],
            ['name' => 'Ethics', 'type' => 'Graduation'],
            ['name' => 'Farm Power and Machinery', 'type' => 'Graduation'],
            ['name' => 'Farm Structure', 'type' => 'Graduation'],
            ['name' => 'Fiqh', 'type' => 'Graduation'],
            ['name' => 'Finance', 'type' => 'Graduation'],
            ['name' => 'Fine Arts', 'type' => 'Graduation'],
            ['name' => 'Fisheries', 'type' => 'Graduation'],
            ['name' => 'Fisheries and Aquaculture', 'type' => 'Graduation'],
            ['name' => 'Fisheries Biology', 'type' => 'Graduation'],
            ['name' => 'Fisheries Management', 'type' => 'Graduation'],
            ['name' => 'Fisheries Technology', 'type' => 'Graduation'],
            ['name' => 'Folklore', 'type' => 'Graduation'],
            ['name' => 'Food Tech. and Rural Industry', 'type' => 'Graduation'],
            ['name' => 'Forestry', 'type' => 'Graduation'],
            ['name' => 'Genetic Engineering', 'type' => 'Graduation'],
            ['name' => 'Genetic Engineering and Biotechnology', 'type' => 'Graduation'],
            ['name' => 'Genetic and Breeding', 'type' => 'Graduation'],
            ['name' => 'Geography', 'type' => 'Graduation'],
            ['name' => 'Geography and Environmental Science', 'type' => 'Graduation'],
            ['name' => 'Geology/Geology and Mining', 'type' => 'Graduation'],
            ['name' => 'Graphics', 'type' => 'Graduation'],
            ['name' => 'Hadith', 'type' => 'Graduation'],
            ['name' => 'History', 'type' => 'Graduation'],
            ['name' => 'History of Music', 'type' => 'Graduation'],
            ['name' => 'Home Economics', 'type' => 'Graduation'],
            ['name' => 'Horticulture', 'type' => 'Graduation'],
            ['name' => 'Industrial', 'type' => 'Graduation'],
            ['name' => 'Industrial Arts', 'type' => 'Graduation'],
            ['name' => 'Information Science and Library Management', 'type' => 'Graduation'],
            ['name' => 'Information Technology', 'type' => 'Graduation'],
            ['name' => 'Information and Communication Technology', 'type' => 'Graduation'],
            ['name' => 'International Law', 'type' => 'Graduation'],
            ['name' => 'International Relations', 'type' => 'Graduation'],
            ['name' => 'Islamic History and Culture', 'type' => 'Graduation'],
            ['name' => 'Islamic Studies', 'type' => 'Graduation'],
            ['name' => 'L.L.B', 'type' => 'Graduation'],
            ['name' => 'Language/Linguistic', 'type' => 'Graduation'],
            ['name' => 'Law/Jurisprudence', 'type' => 'Graduation'],
            ['name' => 'Leather Technology', 'type' => 'Graduation'],
            ['name' => 'Livestock', 'type' => 'Graduation'],
            ['name' => 'Management', 'type' => 'Graduation'],
            ['name' => 'Marine', 'type' => 'Graduation'],
            ['name' => 'Marine Science', 'type' => 'Graduation'],
            ['name' => 'Marketing', 'type' => 'Graduation'],
            ['name' => 'Mass Comm. and Journalism', 'type' => 'Graduation'],
            ['name' => 'Materials Science and Engineering', 'type' => 'Graduation'],
            ['name' => 'Materials Science and Engineering', 'type' => 'Graduation'],
            ['name' => 'Mathematics', 'type' => 'Graduation'],
            ['name' => 'Mechanical', 'type' => 'Graduation'],
            ['name' => 'Medical Technology', 'type' => 'Graduation'],
            ['name' => 'Medicine and Surgery', 'type' => 'Graduation'],
            ['name' => 'Metallurgy', 'type' => 'Graduation'],
            ['name' => 'Microbiology', 'type' => 'Graduation'],
            ['name' => 'Microbiology and Hygienic', 'type' => 'Graduation'],
            ['name' => 'Microwave Engineering', 'type' => 'Graduation'],
            ['name' => 'Mineral', 'type' => 'Graduation'],
            ['name' => 'Mining', 'type' => 'Graduation'],
            ['name' => 'Modern Arabic', 'type' => 'Graduation'],
            ['name' => 'Naval Architecture', 'type' => 'Graduation'],
            ['name' => 'Pali', 'type' => 'Graduation'],
            ['name' => 'Paratrology', 'type' => 'Graduation'],
            ['name' => 'Peace and Conflict', 'type' => 'Graduation'],
            ['name' => 'Persian', 'type' => 'Graduation'],
            ['name' => 'Pharmaceutical Chemistry', 'type' => 'Graduation'],
            ['name' => 'Pharmacy', 'type' => 'Graduation'],
            ['name' => 'Philosophy', 'type' => 'Graduation'],
            ['name' => 'Physical Planning', 'type' => 'Graduation'],
            ['name' => 'Physics', 'type' => 'Graduation'],
            ['name' => 'Plant Pathology', 'type' => 'Graduation'],
            ['name' => 'Political Science', 'type' => 'Graduation'],
            ['name' => 'Population Science', 'type' => 'Graduation'],
            ['name' => 'Poultry Science', 'type' => 'Graduation'],
            ['name' => 'Production Economics', 'type' => 'Graduation'],
            ['name' => 'Psychology', 'type' => 'Graduation'],
            ['name' => 'Public Administration', 'type' => 'Graduation'],
            ['name' => 'Public Finance', 'type' => 'Graduation'],
            ['name' => 'Regional Planning', 'type' => 'Graduation'],
            ['name' => 'Rural Sociology', 'type' => 'Graduation'],
            ['name' => 'Sanskrit', 'type' => 'Graduation'],
            ['name' => 'Social Welfare/Social Work', 'type' => 'Graduation'],
            ['name' => 'Sociology', 'type' => 'Graduation'],
            ['name' => 'Software Engineering', 'type' => 'Graduation'],
            ['name' => 'Soil Water and Environment Science', 'type' => 'Graduation'],
            ['name' => 'Statistics', 'type' => 'Graduation'],
            ['name' => 'Structural', 'type' => 'Graduation'],
            ['name' => 'Surgery and Obstinate', 'type' => 'Graduation'],
            ['name' => 'Tafsir', 'type' => 'Graduation'],
            ['name' => 'Telecommunication Engineering', 'type' => 'Graduation'],
            ['name' => 'Textile Technology', 'type' => 'Graduation'],
            ['name' => 'Town Planning', 'type' => 'Graduation'],
            ['name' => 'Urban and Regional Planning', 'type' => 'Graduation'],
            ['name' => 'Urban Development', 'type' => 'Graduation'],
            ['name' => 'Urdu', 'type' => 'Graduation'],
            ['name' => 'Water and Environment Science', 'type' => 'Graduation'],
            ['name' => 'Water Resource Engineering', 'type' => 'Graduation'],
            ['name' => 'Women Studies', 'type' => 'Graduation'],
            ['name' => 'World Religion', 'type' => 'Graduation'],
            ['name' => 'Zoology', 'type' => 'Graduation'],
            ['name' => 'Others', 'type' => 'Graduation'],
        ];

        $masters_subjects = [
            ['name' => 'Accounting', 'type' => 'Masters'],
            ['name' => 'Anthropology', 'type' => 'Masters'],
            ['name' => 'Applied Chemistry', 'type' => 'Masters'],
            ['name' => 'Applied Physics', 'type' => 'Masters'],
            ['name' => 'Applied Mathematics', 'type' => 'Masters'],
            ['name' => 'Arabic', 'type' => 'Masters'],
            ['name' => 'Archaeology', 'type' => 'Masters'],
            ['name' => 'Bangla', 'type' => 'Masters'],
            ['name' => 'Banking', 'type' => 'Masters'],
            ['name' => 'Biochemistry', 'type' => 'Masters'],
            ['name' => 'Botany', 'type' => 'Masters'],
            ['name' => 'Business Administration', 'type' => 'Masters'],
            ['name' => 'Chemistry', 'type' => 'Masters'],
            ['name' => 'Computer Science', 'type' => 'Masters'],
            ['name' => 'Clinical Psychology', 'type' => 'Masters'],
            ['name' => 'Drama and Music', 'type' => 'Masters'],
            ['name' => 'Development Studies', 'type' => 'Masters'],
            ['name' => 'Economics', 'type' => 'Masters'],
            ['name' => 'Education', 'type' => 'Masters'],
            ['name' => 'English', 'type' => 'Masters'],
            ['name' => 'Finance', 'type' => 'Masters'],
            ['name' => 'Fine Arts', 'type' => 'Masters'],
            ['name' => 'Folklore', 'type' => 'Masters'],
            ['name' => 'Geography', 'type' => 'Masters'],
            ['name' => 'Geography and Environmental Science', 'type' => 'Masters'],
            ['name' => 'History', 'type' => 'Masters'],
            ['name' => 'Home Economics', 'type' => 'Masters'],
            ['name' => 'Hadith', 'type' => 'Masters'],
            ['name' => 'International Relations', 'type' => 'Masters'],
            ['name' => 'Islamic History and Culture', 'type' => 'Masters'],
            ['name' => 'Islamic Studies', 'type' => 'Masters'],
            ['name' => 'Information and Communication Technology', 'type' => 'Masters'],
            ['name' => 'Mass Comm. and Journalism', 'type' => 'Masters'],
            ['name' => 'Law/Jurisprudence', 'type' => 'Masters'],
            ['name' => 'Information Science and Library Management', 'type' => 'Masters'],
            ['name' => 'Language/Linguistic', 'type' => 'Masters'],
            ['name' => 'Management', 'type' => 'Masters'],
            ['name' => 'Marketing', 'type' => 'Masters'],
            ['name' => 'Mathematics', 'type' => 'Masters'],
            ['name' => 'Microbiology', 'type' => 'Masters'],
            ['name' => 'Marine Science', 'type' => 'Masters'],
            ['name' => 'Medical Technology', 'type' => 'Masters'],
            ['name' => 'Pali', 'type' => 'Masters'],
            ['name' => 'Persian', 'type' => 'Masters'],
            ['name' => 'Pharmacy', 'type' => 'Masters'],
            ['name' => 'Philosophy', 'type' => 'Masters'],
            ['name' => 'Physics', 'type' => 'Masters'],
            ['name' => 'Political Science', 'type' => 'Masters'],
            ['name' => 'Psychology', 'type' => 'Masters'],
            ['name' => 'Public Administration', 'type' => 'Masters'],
            ['name' => 'Public Finance', 'type' => 'Masters'],
            ['name' => 'Population Science', 'type' => 'Masters'],
            ['name' => 'Peace and Conflict', 'type' => 'Masters'],
            ['name' => 'Pharmaceutical Chemistry', 'type' => 'Masters'],
            ['name' => 'Sanskrit', 'type' => 'Masters'],
            ['name' => 'Social Welfare/Social Work', 'type' => 'Masters'],
            ['name' => 'Sociology', 'type' => 'Masters'],
            ['name' => 'Soil Water and Environment Science', 'type' => 'Masters'],
            ['name' => 'Statistics', 'type' => 'Masters'],
            ['name' => 'Tafsir', 'type' => 'Masters'],
            ['name' => 'Urdu', 'type' => 'Masters'],
            ['name' => 'Urban Development', 'type' => 'Masters'],
            ['name' => 'World Religion', 'type' => 'Masters'],
            ['name' => 'Women Studies', 'type' => 'Masters'],
            ['name' => 'Water and Environment Science', 'type' => 'Masters'],
            ['name' => 'Zoology', 'type' => 'Masters'],
            ['name' => 'Genetic and Breeding', 'type' => 'Masters'],
            ['name' => 'International Law', 'type' => 'Masters'],
            ['name' => 'Akaid', 'type' => 'Masters'],
            ['name' => 'Graphics', 'type' => 'Masters'],
            ['name' => 'Fiqh', 'type' => 'Masters'],
            ['name' => 'Modern Arabic', 'type' => 'Masters'],
            ['name' => 'History of Music', 'type' => 'Masters'],
            ['name' => 'Drawing and Printing', 'type' => 'Masters'],
            ['name' => 'Industrial Arts', 'type' => 'Masters'],
            ['name' => 'Ethics', 'type' => 'Masters'],
            ['name' => 'Forestry', 'type' => 'Masters'],
            ['name' => 'Criminology and Police Science', 'type' => 'Masters'],
            ['name' => 'Department of Television, Film and Photography', 'type' => 'Masters'],
            ['name' => 'Department of Women and Gender Studies', 'type' => 'Masters'],
            ['name' => 'Department of Criminology', 'type' => 'Masters'],
            ['name' => 'Department of Communication Disorders', 'type' => 'Masters'],
            ['name' => 'Computer Engineering', 'type' => 'Masters'],
            ['name' => 'Computer Science and Engineering', 'type' => 'Masters'],
            ['name' => 'Computer Science and Information Technology', 'type' => 'Masters'],
            ['name' => 'Information Technology', 'type' => 'Masters'],
            ['name' => 'Geology/Geology and Mining', 'type' => 'Masters'],
            ['name' => 'Environmental science', 'type' => 'Masters'],
            ['name' => 'Genetic Engineering and Biotechnology', 'type' => 'Masters'],
            ['name' => 'Materials Science and Engineering', 'type' => 'Masters'],
            ['name' => 'Agriculture', 'type' => 'Masters'],
            ['name' => 'Agriculture Chemistry', 'type' => 'Masters'],
            ['name' => 'Agriculture Co-operatives', 'type' => 'Masters'],
            ['name' => 'Agriculture Economics', 'type' => 'Masters'],
            ['name' => 'Agriculture Engineering', 'type' => 'Masters'],
            ['name' => 'Agriculture Finance', 'type' => 'Masters'],
            ['name' => 'Agriculture Marketing', 'type' => 'Masters'],
            ['name' => 'Agriculture Science', 'type' => 'Masters'],
            ['name' => 'Agriculture Soil Science', 'type' => 'Masters'],
            ['name' => 'Animal Husbandry', 'type' => 'Masters'],
            ['name' => 'Agronomy and Aquaculture', 'type' => 'Masters'],
            ['name' => 'Agronomy and Aquaculture Extension', 'type' => 'Masters'],
            ['name' => 'Anatomy and Histology', 'type' => 'Masters'],
            ['name' => 'Agronomy', 'type' => 'Masters'],
            ['name' => 'Anatomology', 'type' => 'Masters'],
            ['name' => 'Animal Breeding and Genetic', 'type' => 'Masters'],
            ['name' => 'Animal Science', 'type' => 'Masters'],
            ['name' => 'Animal Nutrition', 'type' => 'Masters'],
            ['name' => 'Agriculture Water Management', 'type' => 'Masters'],
            ['name' => 'Agriculture Extension', 'type' => 'Masters'],
            ['name' => 'Agro Forestry', 'type' => 'Masters'],
            ['name' => 'Agriculture Statistics', 'type' => 'Masters'],
            ['name' => 'Agr.Co-operative and Marketing', 'type' => 'Masters'],
            ['name' => 'Bio-Technology', 'type' => 'Masters'],
            ['name' => 'Corp Botany', 'type' => 'Masters'],
            ['name' => 'Dairy Science', 'type' => 'Masters'],
            ['name' => 'Doc.of Veterinary Science', 'type' => 'Masters'],
            ['name' => 'Fisheries', 'type' => 'Masters'],
            ['name' => 'Fisheries and Aquaculture', 'type' => 'Masters'],
            ['name' => 'Fisheries Biology', 'type' => 'Masters'],
            ['name' => 'Fisheries Management', 'type' => 'Masters'],
            ['name' => 'Fisheries Technology', 'type' => 'Masters'],
            ['name' => 'Forestry', 'type' => 'Masters'],
            ['name' => 'Farm Power and Machinery', 'type' => 'Masters'],
            ['name' => 'Food Tech. and Rural Industry', 'type' => 'Masters'],
            ['name' => 'Farm Structure', 'type' => 'Masters'],
            ['name' => 'Horticulture', 'type' => 'Masters'],
            ['name' => 'Livestock', 'type' => 'Masters'],
            ['name' => 'Microbiology and Hygienic', 'type' => 'Masters'],
            ['name' => 'Production Economics', 'type' => 'Masters'],
            ['name' => 'Plant Pathology', 'type' => 'Masters'],
            ['name' => 'Paratrology', 'type' => 'Masters'],
            ['name' => 'Poultry Science', 'type' => 'Masters'],
            ['name' => 'Rural Sociology', 'type' => 'Masters'],
            ['name' => 'Surgery and Obstinate', 'type' => 'Masters'],
            ['name' => 'Business Studies', 'type' => 'Masters'],
            ['name' => 'Architecture', 'type' => 'Masters'],
            ['name' => 'Chemical', 'type' => 'Masters'],
            ['name' => 'Civil', 'type' => 'Masters'],
            ['name' => 'Electrical', 'type' => 'Masters'],
            ['name' => 'Electrical and Electronics', 'type' => 'Masters'],
            ['name' => 'Electronic', 'type' => 'Masters'],
            ['name' => 'Genetic Engineering', 'type' => 'Masters'],
            ['name' => 'Industrial', 'type' => 'Masters'],
            ['name' => 'Leather Technology', 'type' => 'Masters'],
            ['name' => 'Marine', 'type' => 'Masters'],
            ['name' => 'Mechanical', 'type' => 'Masters'],
            ['name' => 'Metallurgy', 'type' => 'Masters'],
            ['name' => 'Mineral', 'type' => 'Masters'],
            ['name' => 'Mining', 'type' => 'Masters'],
            ['name' => 'Naval Architecture', 'type' => 'Masters'],
            ['name' => 'Physical Planning', 'type' => 'Masters'],
            ['name' => 'Regional Planning', 'type' => 'Masters'],
            ['name' => 'Structural', 'type' => 'Masters'],
            ['name' => 'Textile Technology', 'type' => 'Masters'],
            ['name' => 'Town Planning', 'type' => 'Masters'],
            ['name' => 'Urban and Regional Planning', 'type' => 'Masters'],
            ['name' => 'Telecommunication Engineering', 'type' => 'Masters'],
            ['name' => 'Computer Science', 'type' => 'Masters'],
            ['name' => 'Microwave Engineering', 'type' => 'Masters'],
            ['name' => 'A and B Section of A.M.I.E', 'type' => 'Masters'],
            ['name' => 'Environmental Engineering', 'type' => 'Masters'],
            ['name' => 'Aeronautical Engineering', 'type' => 'Masters'],
            ['name' => 'Software Engineering', 'type' => 'Masters'],
            ['name' => 'Medicine and Surgery', 'type' => 'Masters'],
            ['name' => 'Dental Surgery', 'type' => 'Masters'],
            ['name' => 'Computer Engineering', 'type' => 'Masters'],
            ['name' => 'Computer Science and Engineering', 'type' => 'Masters'],
            ['name' => 'Computer Science and Information Technology', 'type' => 'Masters'],
            ['name' => 'Information and Communication Technology', 'type' => 'Masters'],
            ['name' => 'Electronics and Communication Engineering', 'type' => 'Masters'],
            ['name' => 'Water Resource Engineering', 'type' => 'Masters'],
            ['name' => 'Materials Science and Engineering', 'type' => 'Masters'],
            ['name' => 'Others', 'type' => 'Masters'],
        ];

        DB::table('subjects')->insert($ssc_subjects);
        DB::table('subjects')->insert($hsc_subjects);
        DB::table('subjects')->insert($graduation_subjects);
        DB::table('subjects')->insert($masters_subjects);
    }
}
